import type { QuizItem } from "./discovery-quizzes";

function q(prompt: string, axes: Record<string, number>): QuizItem {
  return { prompt, axes };
}

export const LIKERT_OPTIONS = [
  { label: "Strongly disagree", value: 0 },
  { label: "Disagree", value: 1 },
  { label: "Slightly disagree", value: 2 },
  { label: "Unsure", value: 3 },
  { label: "Slightly agree", value: 4 },
  { label: "Agree", value: 5 },
  { label: "Strongly agree", value: 6 },
] as const;

export const QUICK_LABELS: Record<string, string> = {
  dominance: "Dominance",
  submission: "Submission",
  sensation: "Sensation & Impact",
  psychological: "Psychological Play",
  bondage: "Bondage & Restraint",
  trust: "Trust & Vulnerability",
  adventurous: "Adventurousness",
};

export const QUICK_SHORT_LABELS: Record<string, string> = {
  dominance: "Dominance",
  submission: "Submission",
  sensation: "Sensation",
  psychological: "Psychological",
  bondage: "Bondage",
  trust: "Trust",
  adventurous: "Adventure",
};

export const QUICK_BLURBS: Record<string, string> = {
  dominance: "You may enjoy taking the lead, giving direction, or creating structure within an agreed power dynamic.",
  submission: "You may enjoy yielding decisions, following a lead, or offering control to someone you trust.",
  sensation: "You may be drawn to intensity on the body — impact, temperature, ache, or overload — when it is paced and wanted.",
  psychological: "You may be more turned on by the head than the toy: praise, protocol, mind games, or being seen.",
  bondage: "You may want restriction — rope, cuffs, being held still, or holding someone still — as the point of the scene.",
  trust: "You may get heat from dropping your guard, being held through it, or being the person someone can drop with.",
  adventurous: "You may like trying new shapes, pushing a known edge, or saying yes to experiments that stay inside consent.",
};

export const FULL_LABELS: Record<string, string> = {
  dominant: "Dominant",
  submissive: "Submissive",
  switch: "Switch",
  master: "Master/Mistress",
  slave: "Slave",
  daddy: "Daddy/Mommy",
  little: "Little",
  sadist: "Sadist",
  masochist: "Masochist",
  rigger: "Rigger",
  "rope-bunny": "Rope Bunny",
  degrader: "Degrader",
  degradee: "Degradee",
  hunter: "Primal (Hunter)",
  prey: "Primal (Prey)",
  voyeur: "Voyeur",
  exhibitionist: "Exhibitionist",
  brat: "Brat",
  "brat-tamer": "Brat Tamer",
  owner: "Owner",
  pet: "Pet",
  vanilla: "Vanilla",
  experimentalist: "Experimentalist",
  "non-hierarchical": "Non-Hierarchical",
};

export const FULL_BLURBS: Record<string, string> = {
  dominant: "You may enjoy taking the lead, giving direction, or creating structure within an agreed power dynamic.",
  submissive: "You may enjoy following, serving, or handing decisions to someone whose lead you trust.",
  switch: "You may want both seats — leading some nights, following others — and the trade itself can be the heat.",
  master: "You may want a fuller authority than a scene: rules, titles, and a dynamic that still exists when the clothes are on.",
  slave: "You may want to belong in a deeper, more total way — service, obedience, and being claimed as more than a scene partner.",
  daddy: "You may like a guiding, caring authority — structure mixed with warmth, not only strictness.",
  little: "You may want to drop into a smaller, held headspace and be looked after by someone steady.",
  sadist: "You may enjoy giving pain or intensity on purpose, watching it land, and pacing it as care.",
  masochist: "You may enjoy receiving pain or intensity as pleasure, release, or proof of trust.",
  rigger: "You may enjoy tying, wrapping, and composing a body in rope or restraint.",
  "rope-bunny": "You may enjoy being tied, held in rope, and giving your movement to someone else's knots.",
  degrader: "You may enjoy using filthy or lowering language as a scripted, consented act — then repairing it.",
  degradee: "You may enjoy being spoken to that way, when the words were agreed and the landing is kind.",
  hunter: "You may enjoy chase, catch, pin — a predatory heat in a house you have both safetied.",
  prey: "You may enjoy being hunted, caught, and held, with a tap that still works.",
  voyeur: "You may get more from watching than from being the one on display.",
  exhibitionist: "You may get more from being seen — by a partner, a mirror, a chosen audience — than from watching.",
  brat: "You may poke the frame on purpose, and want to be caught, not ignored or actually hurt.",
  "brat-tamer": "You may like the smirk, the chase of the rule, and gathering someone back in without trapping them.",
  owner: "You may want the language of mine — collar, claim, everyday belonging — with a clock and an out.",
  pet: "You may want to stop being in charge of yourself for a while: cushion, name, simple tasks, then your name back.",
  vanilla: "You may prefer affection, sex, and closeness without power play, and that is a complete profile.",
  experimentalist: "You may like trying new kinks more than settling on a single identity — curiosity as the orientation.",
  "non-hierarchical": "You may want kink and intensity without a Dominant/submissive ranking — play as equals.",
};

export const BDSM_QUICK_QUESTIONS: QuizItem[] = [
  q("I like being the one in charge during sex or play.", { dominance: 1 }),
  q("Giving orders and watching my partner follow them turns me on.", { dominance: 1 }),
  q("I naturally gravitate toward holding the lead.", { dominance: 1 }),
  q("I like it when my partner takes control during intimate moments.", { submission: 1 }),
  q("Following a clear instruction can be hotter than deciding the night myself.", { submission: 1 }),
  q("Having rules to follow during play makes me feel settled.", { submission: 1 }),
  q("I like some scenes where I lead and some where I follow.", { dominance: 0.5, submission: 0.5 }),
  q("I like giving pain or strong sensation during play, when it is wanted.", { sensation: 1 }),
  q("I like receiving pain or strong sensation during play.", { sensation: 1 }),
  q("Paddles, floggers, or crops interest me — using them or taking them.", { sensation: 1 }),
  q("I want to explore sensation at intensities I choose.", { sensation: 1 }),
  q("Being praised during play makes me melt.", { psychological: 1 }),
  q("I like praising my partner during play.", { psychological: 1 }),
  q("Dirty talk that stays inside what we agreed turns me on.", { psychological: 1 }),
  q("Making a partner wait or beg, with consent, is a turn-on.", { psychological: 1 }),
  q("I like tying my partner with rope or cuffs.", { bondage: 1 }),
  q("Being tied or held still by a partner excites me.", { bondage: 1 }),
  q("I like blindfolding a partner, or being blindfolded.", { bondage: 0.7, psychological: 0.3 }),
  q("Play works better for me when we say what we want and what is off limits.", { trust: 1 }),
  q("I can drop my guard with a partner and let them see me messy or needy.", { trust: 1 }),
  q("Check-ins and aftercare are part of what makes play good, not extra.", { trust: 1 }),
  q("Trying a kink I have not done before excites me, if we can stop it.", { adventurous: 1 }),
  q("I like suggesting new things so sex does not feel repetitive.", { adventurous: 1 }),
  q("I would enjoy going to a kink event or club that felt safe for me.", { adventurous: 1 }),
  q("I like trying intense activities that come close to my limits, not past them.", { adventurous: 1 }),
];

export const BDSM_FULL_QUESTIONS: QuizItem[] = [
  q("I like telling a partner what to do, and having them do it.", { dominant: 1 }),
  q("Being in charge during a scene feels natural to me.", { dominant: 1 }),
  q("I enjoy giving instructions within an agreed power dynamic.", { dominant: 1 }),
  q("I want the last word on what we do tonight, once we have agreed the limits.", { dominant: 1 }),
  q("People relaxing because I am handling it is a turn-on.", { dominant: 1 }),
  q("I like letting my partner take control during intimate moments.", { submissive: 1 }),
  q("I enjoy receiving instructions within an agreed power dynamic.", { submissive: 1 }),
  q("Following a clear order can be hotter than inventing the night myself.", { submissive: 1 }),
  q("I want someone else to decide the shape of the evening, with a way to stop.", { submissive: 1 }),
  q("Kneeling, waiting, or asking permission can feel like coming home.", { submissive: 1 }),
  q("I like switching between taking control and letting my partner take control.", { switch: 1 }),
  q("Some nights I need to lead. Other nights I need to follow. Both are me.", { switch: 1 }),
  q("I get bored if I only ever take charge, or only ever give it up.", { switch: 1 }),
  q("I can hold someone and then ask to be held, without it breaking us.", { switch: 1 }),
  q("Trading who is in charge from one scene to the next keeps things alive for me.", { switch: 1 }),
  q("I like a more formal dynamic where I am in charge and my partner uses a title.", { master: 1 }),
  q("I would enjoy writing standing rules for times when I am in control.", { master: 1 }),
  q("Protocol and honorifics appeal to me more than a loose, one-off scene.", { master: 1 }),
  q("I want authority that still exists when the clothes are on.", { master: 1 }),
  q("I take responsibility for what I open, including the boring parts of running a dynamic.", { master: 1 }),
  q("I like a role where I belong to my partner while they are in charge.", { slave: 1 }),
  q("Making service a real part of the relationship would feel fulfilling.", { slave: 1 }),
  q("Written rules feel meaningful when my partner is in control.", { slave: 1 }),
  q("I want to be claimed as more than a play partner — with a way out that still works.", { slave: 1 }),
  q("Obedience and belonging are part of my sexuality, not only a favour.", { slave: 1 }),
  q("I like taking a nurturing caregiver role with my partner.", { daddy: 1 }),
  q("Comforting and guiding someone in a Little headspace feels like me.", { daddy: 1 }),
  q("Structure mixed with warmth is the kind of authority I want to give.", { daddy: 1 }),
  q("I like looking after food, rest, and a held day — not only sex.", { daddy: 1 }),
  q("Praise and guidance from me should feel like a home, not a test.", { daddy: 1 }),
  q("I like taking a Little role where I can feel playful and cared for.", { little: 1 }),
  q("I like setting adult responsibilities aside for a while, on purpose.", { little: 1 }),
  q("Being cared for — snacks, voice, simple rules — appeals to me.", { little: 1 }),
  q("I can enjoy a Little role even when I am not pretending to be younger.", { little: 1 }),
  q("I want a caregiver more than I want a tyrant.", { little: 1 }),
  q("I like giving my partner pain during play, when they want it.", { sadist: 1 }),
  q("I like finding the kinds and levels of pain my partner enjoys.", { sadist: 1 }),
  q("I like hitting with paddles, floggers, or crops.", { sadist: 1 }),
  q("Pacing hurt — and stopping it — is a skill I want to use.", { sadist: 1 }),
  q("I like the look of marks we both chose.", { sadist: 1 }),
  q("I like receiving pain during intimate play.", { masochist: 1 }),
  q("The rush of taking pain during play is something I want.", { masochist: 1 }),
  q("I like being hit with paddles, floggers, or crops.", { masochist: 1 }),
  q("Ache I asked for can put me in my body in a way vanilla sex does not.", { masochist: 1 }),
  q("I can like pain without wanting to be degraded. They are different asks.", { masochist: 1 }),
  q("I like using rope to tie my partner.", { rigger: 1 }),
  q("I like making restraint look considered, not only tight.", { rigger: 1 }),
  q("I would enjoy learning more complex ties.", { rigger: 1 }),
  q("The craft of bondage — tension, safety, a body in a shape I made — is a draw.", { rigger: 1 }),
  q("I like being the person with the rope and the plan for how they come out of it.", { rigger: 1 }),
  q("Being tied in a position that works for my body excites me.", { "rope-bunny": 1 }),
  q("I like how rope feels against my skin.", { "rope-bunny": 1 }),
  q("Being snugly wrapped or partly tied, while I can still move, appeals.", { "rope-bunny": 1 }),
  q("Being comfortably restrained helps me relax and stop overthinking.", { "rope-bunny": 1 }),
  q("Giving up movement to someone else's knots is a specific hunger.", { "rope-bunny": 1 }),
  q("I like using lowering or filthy language as a consented part of play.", { degrader: 1 }),
  q("I like choosing humiliating words that actually turn my partner on.", { degrader: 1 }),
  q("I like treating my partner like an object during degradation play they asked for.", { degrader: 1 }),
  q("I can use hard words in a scene and still see my partner as my equal when it ends.", { degrader: 1 }),
  q("Aftercare after verbal play should be extra kind. That is part of running it.", { degrader: 1 }),
  q("Being called degrading names during play can turn me on.", { degradee: 1 }),
  q("Humiliating words that fit what I asked for can work. Surprise humiliation usually does not.", { degradee: 1 }),
  q("Being treated like an object during a timed scene can turn me on.", { degradee: 1 }),
  q("I want the opposite sentences afterwards, said as true.", { degradee: 1 }),
  q("I can like degradation even when there is no pain.", { degradee: 1 }),
  q("I like physical, animal-like play that feels instinctive instead of scripted.", { hunter: 1 }),
  q("I enjoy growling, biting, or rough movement during primal play.", { hunter: 1 }),
  q("I like chasing my partner like prey during primal play.", { hunter: 1 }),
  q("A grab and a hold against a wall we agreed was safe is more me than formal protocol.", { hunter: 1 }),
  q("Prey who can stop being prey in a full sentence is the only prey I want.", { hunter: 1 }),
  q("Being chased and caught during primal play turns me on.", { prey: 1 }),
  q("I want to be hunted, caught, and held, with a way to stop that still works.", { prey: 1 }),
  q("Running and being caught is hotter for me than kneeling on a cushion.", { prey: 1 }),
  q("A pin, a breath, my name back: that landing matters as much as the catch.", { prey: 1 }),
  q("I like feeling taken — in a scene we built — more than feeling instructed.", { prey: 1 }),
  q("Watching adults have sex turns me on when everyone agrees I can watch.", { voyeur: 1 }),
  q("I like watching kink play without taking part, when that was agreed.", { voyeur: 1 }),
  q("Watching my partner put on a sexual show for me turns me on.", { voyeur: 1 }),
  q("I get more heat from seeing than from being on display.", { voyeur: 1 }),
  q("A mirror I watch them in can be enough audience.", { voyeur: 1 }),
  q("Being watched during kink play turns me on when everyone involved has agreed.", { exhibitionist: 1 }),
  q("I like showing my body to people who have agreed to watch.", { exhibitionist: 1 }),
  q("I would enjoy my partner showing me off to an audience that wants to watch.", { exhibitionist: 1 }),
  q("Being looked at can be the whole scene. Sex can wait.", { exhibitionist: 1 }),
  q("A little risk of being almost-caught, still reversible, interests me.", { exhibitionist: 1 }),
  q("I like playfully disobeying as part of brat play.", { brat: 1 }),
  q("I have fun teasing or provoking my partner during brat play.", { brat: 1 }),
  q("I like breaking a small rule so my partner gives me a playful consequence.", { brat: 1 }),
  q("I like being cheeky to get a reaction, then being gathered back in.", { brat: 1 }),
  q("If no one plays back, bratting just feels lonely. I need the catch.", { brat: 1 }),
  q("I like finding clever ways to get a playfully defiant partner to cooperate.", { "brat-tamer": 1 }),
  q("I like giving playful consequences for bratty behaviour.", { "brat-tamer": 1 }),
  q("Brats are fun for me. Actual contempt is not.", { "brat-tamer": 1 }),
  q("I will gather someone who pushed, and I will not invent a new punishment in anger.", { "brat-tamer": 1 }),
  q("The game is: they push, I catch, we both still like each other.", { "brat-tamer": 1 }),
  q("I like giving a partner a collar to show they are mine, as play we both meant.", { owner: 1 }),
  q("Everyday belonging — not only bedroom belonging — interests me.", { owner: 1 }),
  q("I like leaving a temporary mark during ownership play we agreed.", { owner: 1 }),
  q("I like training a partner when they play my pet.", { owner: 1, pet: 0.2 }),
  q("Mine is a word I want to use, with a clock and an out.", { owner: 1 }),
  q("I would enjoy playing a pet role for my partner.", { pet: 1 }),
  q("Wearing a collar to show I am my partner's pet would make me feel close to them.", { pet: 1 }),
  q("Stopping being in charge of myself for a timed evening is the point.", { pet: 1 }),
  q("I like being kept, not humiliated, unless humiliation was listed.", { pet: 1 }),
  q("Simple tasks, a cushion, then my name back at the end, works for me.", { pet: 1 }),
  q("I prefer sex without BDSM roles most of the time.", { vanilla: 1 }),
  q("I currently have little interest in BDSM activities.", { vanilla: 1 }),
  q("Gentle, mutual, no protocol — that is a complete good night.", { vanilla: 1 }),
  q("I can enjoy kink ideas in theory and still prefer a night that stays ordinary.", { vanilla: 1 }),
  q("I do not need a scene to feel close. I might not want one.", { vanilla: 1 }),
  q("Trying a kink I have not explored before excites me.", { experimentalist: 1 }),
  q("I like suggesting new things so sex does not feel repetitive.", { experimentalist: 1 }),
  q("I like trying intense activities that come close to my limits.", { experimentalist: 1 }),
  q("A menu I have not used yet is more exciting than a title I already know.", { experimentalist: 1 }),
  q("Curiosity is my orientation as much as Dominant or submissive is.", { experimentalist: 1 }),
  q("I enjoy BDSM activities without either partner taking control of the other.", { "non-hierarchical": 1 }),
  q("I like sharing control during kink without either partner being in charge.", { "non-hierarchical": 1 }),
  q("I would rather have sex without either partner being the boss.", { "non-hierarchical": 1 }),
  q("Top and bottom can be technical, not a ranking of who we are.", { "non-hierarchical": 1 }),
  q("A scene between equals, with heat and a safeword, is enough structure for me.", { "non-hierarchical": 1 }),
  q("I think about rope specifically — tying or being tied — often enough to call it an interest.", { rigger: 0.5, "rope-bunny": 0.5 }),
  q("Pain that I give or take is a real part of my sexuality, not a maybe.", { sadist: 0.5, masochist: 0.5 }),
  q("Being watched or watching is a hunger I would put on a list.", { voyeur: 0.5, exhibitionist: 0.5 }),
  q("Care-and-control, not only sex-and-control, belongs in my profile.", { daddy: 0.5, little: 0.5 }),
  q("I want a partner who will compare this profile with me, not a score I hide.", { experimentalist: 0.4, vanilla: 0.2 }),
];
