import { IDEA_CATEGORIES } from "./idea-bank";

export type LibraryNote = {
  key: string;
  title: string;
  category: string;
  subcategory: string;
  sort: number;
  body: string;
};

function p(text: string) {
  return `<p>${text}</p>`;
}
function h(text: string) {
  return `<h2>${text}</h2>`;
}
function h3(text: string) {
  return `<h3>${text}</h3>`;
}
function ul(...items: string[]) {
  return `<ul>${items.map((item) => `<li>${item}</li>`).join("")}</ul>`;
}
function ol(...items: string[]) {
  return `<ol>${items.map((item) => `<li>${item}</li>`).join("")}</ol>`;
}
function callout(text: string) {
  return `<blockquote><p><strong>Hold this.</strong> ${text}</p></blockquote>`;
}
function doc(...parts: string[]) {
  return parts.join("");
}

export const NOTE_LIBRARY_CATEGORIES: { value: string; label: string; parent?: string }[] = [
  { value: "education", label: "Education" },
  { value: "reference", label: "Reference", parent: "education" },
  { value: "how-to", label: "How-to", parent: "education" },
  { value: "exercises", label: "Activities" },
  { value: "self", label: "Self", parent: "exercises" },
  { value: "partner", label: "Partner", parent: "exercises" },
  { value: "dynamic", label: "Dynamic", parent: "exercises" },
  { value: "kinks", label: "Kinks", parent: "exercises" },
  { value: "communication", label: "Communication", parent: "exercises" },
  { value: "play", label: "Play", parent: "exercises" },
  { value: "roles", label: "Roles", parent: "exercises" },
  { value: "bratting", label: "Bratting", parent: "exercises" },
  { value: "body", label: "Body", parent: "exercises" },
  ...IDEA_CATEGORIES,
];

export function isLibraryNote(entry: { meta?: Record<string, string> | null }) {
  return Boolean(entry.meta?.libraryKey);
}

export function plainExcerpt(html: string, max = 220) {
  const text = html
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&/g, "&")
    .replace(/</g, "<")
    .replace(/>/g, ">")
    .replace(/\s+/g, " ")
    .trim();
  if (text.length <= max) return text;
  return `${text.slice(0, max).replace(/\s+\S*$/, "").trim()}…`;
}

export const NOTES_LIBRARY: LibraryNote[] = [
  {
    key: "edu-kinks",
    title: "A map of kinks",
    category: "education",
    subcategory: "reference",
    sort: 10,
    body: doc(
      p("Kink is a family of tastes, not a ladder. Use this as a map: names, what they tend to feel like, and what you actually need to say out loud before you try them. Nothing here is permission to skip a negotiation, a safeword, or aftercare."),
      callout("If it involves breath, blood, fire, electricity, or leaving someone bound and alone, it is edge play. Study it. Do not improvise it drunk. Have a way out that does not depend on the person in the scene keeping their nerve."),
      h("Power and protocol"),
      ul(
        "<strong>Dominance and submission.</strong> Authority given, not stolen. Negotiate what the Dominant decides, what stays with the submissive, and what is theatre versus standing rule.",
        "<strong>Service.</strong> Care, errands, ritual, body service. The kink is usefulness done well — and being seen doing it.",
        "<strong>Ownership and protocol.</strong> Titles, collars, rules, kneeling, speech restrictions. The charge is in the structure. Write the rules down. Review them when you are not high on a scene.",
        "<strong>Brat and tamer.</strong> Push and catch. The brat tests the frame; the tamer holds it without collapsing into real anger. See the how-to notes.",
      ),
      h("Body and sensation"),
      ul(
        "<strong>Impact.</strong> Hand, paddle, flogger, cane, crop. Negotiate implements, targets (avoid kidneys, spine, joints, throat), warm-up, and how you will check in. Bruises are not proof of a good scene.",
        "<strong>Bondage.</strong> Cuffs, rope, tape, furniture, being held. Circulation, nerves, joints, and a cutting tool in reach. Never around the neck. Never leave a bound person.",
        "<strong>Sensation.</strong> Ice, wax, feathers, Wartenberg, vibration, teasing. Often a gentler door into intensity.",
        "<strong>Temperature and wax.</strong> Low-temp toy wax only. Test on yourself first. No wax on face, genitals, or broken skin unless you both know the risk.",
        "<strong>Electro.</strong> Only on toys made for bodies. Never across the chest. Never if there is a heart condition, implant, or pregnancy.",
        "<strong>Clamps and pressure.</strong> Time-box them. Blood returning hurts more than going on. That after-sting is part of the scene — warn them.",
      ),
      h("Mind and story"),
      ul(
        "<strong>Praise and degradation.</strong> Opposite doors into the same room: being seen. Degradation that uses a real wound is not edgy, it is careless. Make a list of words that are in, words that are out, and words that are only in-scene.",
        "<strong>Exhibition and voyeur.</strong> Being watched, watching, or the idea of it. Public play must not involve non-consenting people. A window fantasy is not a street.",
        "<strong>Primal.</strong> Chase, wrestle, bite, growl. Agree on what “fight” means, where biting is allowed, and the word that turns the animal off.",
        "<strong>Pet play.</strong> Handler and pet, gear, speech limits, care. It is adult roleplay between adults.",
        "<strong>Medical / clinical.</strong> Exam, gloves, orders, clinical voice. Real medical acts (injections, cutting) are not costume. Leave them to people trained for them.",
        "<strong>Fear play and CNC.</strong> Consensual non-consent is a <em>scripted</em> loss of control, negotiated when everyone can still think. It needs a safeword that always works, a non-verbal signal, aftercare, and a sober yes. It is not a loophole.",
      ),
      h("Sex, control, and the rest"),
      ul(
        "<strong>Orgasm control and chastity.</strong> Tease, deny, schedule, cage. Hydration, skin, and a release plan if swelling or panic shows up. A key the Dominant cannot lose.",
        "<strong>Anal and pegging.</strong> Relax, lube, go slower than pride wants. Nails short. Stop for sharp pain. Aftercare includes a bathroom plan without shame.",
        "<strong>Body worship.</strong> Boots, cock, cunt, chest, feet — attention as devotion.",
        "<strong>Gags and silence.</strong> A gagged person needs a non-verbal safeword (drop a bell, tap twice, hold an object and release it). Never gag someone with a blocked nose or who cannot breathe easily.",
        "<strong>Breath play.</strong> Choking and smothering can kill with no warning and no time to safeword. Many experienced people refuse it. If you still go near it, study from qualified educators, never compress the front of the neck as a casual move, and treat “just a little” as a lie you tell yourselves.",
      ),
      h("How to use the map"),
      ol(
        "Each of you marks: a curious yes, a maybe later, a hard no. Do it separately. Compare.",
        "For every curious yes, write one sentence: what you hope it feels like, and one fear.",
        "Pick one item. Negotiate a small version. Run it. Debrief the next day, not only in the afterglow.",
        "Nothing moves from no to yes because a scene went well. Nos stay nos until the person who owns them reopens them.",
      ),
      p("Want the activity version? Use <em>Explore a kink together</em> under Activities."),
    ),
  },
  {
    key: "edu-toys",
    title: "Toys and how to use them",
    category: "education",
    subcategory: "reference",
    sort: 20,
    body: doc(
      p("A toy is a tool. The scene is still the two of you. Buy body-safe, learn the material, and introduce one new thing at a time so you can tell what actually worked."),
      h("Materials that belong in a body"),
      ul(
        "<strong>Platinum silicone, borosilicate glass, stainless steel.</strong> Non-porous. Wash, boil if the maker says so, and they can last years.",
        "<strong>ABS plastic, some hard toys.</strong> Fine if they are actually body-safe and seamless.",
        "<strong>TPE, jelly, “mystery rubber”, unmarked cheap toys.</strong> Porous. They hold bacteria. Do not share. Consider a condom over them, or replace them.",
        "<strong>Leather and fabric.</strong> For outside the body. Condition leather. Do not use a porous flogger on broken skin and then on someone else.",
      ),
      h("Lube"),
      ul(
        "<strong>Water-based.</strong> Works with almost everything, including silicone toys and latex. Reapply. It dries.",
        "<strong>Silicone-based.</strong> Long-lasting. Not on silicone toys — it can melt the surface. Good for water play.",
        "<strong>Oil-based.</strong> Ruins latex. Messy. Some people like it for hands and external massage only.",
        "If it stings and it is not meant to, stop. Flavoured and warming lubes can irritate.",
      ),
      h("By type"),
      h3("Vibrators"),
      p("Bullets for precise spots, wands for broad and overwhelming, air-pulse for external suction, rabbits for split attention. Start low. Hold still before you chase. A wand on the perineum, over pants, or on the glans can be a lot — ask, then watch their breathing, not only their mouth."),
      h3("Plugs and anal toys"),
      p("A flared base is not optional. Training plugs go up in size across weeks, not one evening. Put lube on the toy and the body. Aim toward the navel, not “up.” If they bear down gently it often enters easier than pushing. Prostate / p-spot toys have a curve for a reason — let them show you the angle. Time in should have a time out. Numbness or sharp pain means out."),
      h3("Dildos, straps, sleeves"),
      p("Harness fit matters more than length. Start smaller than ego. Double-ended needs communication about pace. Sleeves and extenders can rub — lube both sides. Pegging: the receiver sets depth until they ask for more."),
      h3("Rings and constriction"),
      p("Cock rings go on a semi, sit behind the testicles if that is the design, and come off if colour, cold, or numbness shows. Never sleep in a tight ring. Metal rings need a plan if the erection will not fade (cold, time, medical help — not shame)."),
      h3("Clamps"),
      p("Nipples, labia, skin. Adjustable is kinder than cheap spring clips. Seconds to a few minutes for new bodies. Take them off as part of the scene; the blood-return ache is intense. No clamps on the throat, nose, or genitals until you know that body."),
      h3("Impact toys"),
      p("Hand first, so you learn the body. Then paddle (thud), flogger (thud or sting by fall material), crop (sting, small target), cane (sting, skilled only). Wrap around a hip or thigh is how people get hurt. Land flat. Look at the skin between strikes. White that does not pink up, or pain that feels electric down a limb, is a stop."),
      h3("Gags, collars, bits"),
      p("Collars: not load-bearing. Do not yank a person by the neck. Gags: start with a bit they can spit out. Have a drop-signal. Drool is normal; mock it only if that is the negotiated flavour."),
      h3("Remote and app toys"),
      p("Agree the rooms they may be on in. Public play cannot involve unsuspecting people. Batteries die at the worst time — have a word that means “off, now.”"),
      h("Care and sharing"),
      ol(
        "Wash before and after. Toy cleaner or mild soap and water. Silicone and steel can often boil. Follow the maker.",
        "Do not share porous toys. For non-porous, wash; a condom is extra insurance between partners or holes.",
        "Let them dry. Store clean, separate from keys and lint.",
        "Inspect for tears. A nicked silicone toy is a retirement.",
      ),
      h("How to bring a toy in"),
      ol(
        "Show it out of scene. Let them hold it. Say what you want it to do.",
        "Agree where it may go, for how long, and the safeword.",
        "Use it for a short scene. Debrief: too much, not enough, never again, again please.",
        "Photograph it into the Catalogue if you want it in rotation — care notes, intensity, whose body it is for.",
      ),
    ),
  },
  {
    key: "edu-restraints",
    title: "Restraints and how to use them",
    category: "education",
    subcategory: "reference",
    sort: 30,
    body: doc(
      p("Restraint is not the knot. It is the decision to stay, and the other person’s job to make staying survivable. Bondage that looks pretty and wrecks a nerve is a failure."),
      callout("Never leave a bound person. Never restrain the neck. Keep EMT shears or a cutter in reach — not in another room. If they are gagged, they need a non-verbal safeword you will actually see."),
      h("What you are choosing between"),
      ul(
        "<strong>Leather or vegan cuffs.</strong> Fast, kind on skin, buckle or clip. Two-finger space. Clip to a D-ring; do not trust fashion hardware.",
        "<strong>Metal cuffs.</strong> Heavy psychologically. Easy to over-tighten. Padded or not at all for long holds. Know where the key is. Have a spare.",
        "<strong>Velcro and beginner kits.</strong> Fine for under-the-bed and first nights. They give. That is a feature.",
        "<strong>Rope.</strong> Slow, intimate, versatile. Also where beginners hurt people. Learn a single-column tie from a reputable teacher before you load a joint. No rope on the neck. No suspension until you are actually trained — furniture height is not “almost suspension.”",
        "<strong>Tape, wrap, mummification.</strong> Heat, panic, and no circulation feedback. Keep sessions short. Scissors ready. Never cover the nose.",
        "<strong>Spreader bars, hogties, furniture.</strong> Change the leverage on shoulders and knees. Hogties compress the chest — watch breathing. Benches and St Andrew’s crosses need padding and a way down that is not “figure it out while crying.”",
        "<strong>Body holding.</strong> Pins, folds, sitting on thighs. Still bondage. Still needs a word. Joints still have angles they do not like.",
      ),
      h("The checks that are not optional"),
      ol(
        "<strong>Colour and temperature.</strong> Hands and feet should not go white, blue, or ice-cold.",
        "<strong>Sensation.</strong> Can they wiggle fingers and toes? Any numbness, pins and needles, or electric zing — untie that limb now. Nerves do not always warn you twice.",
        "<strong>Capillary refill.</strong> Press a nail bed. Colour should return in a couple of seconds.",
        "<strong>Breathing and talk.</strong> If they cannot take a full breath, or their words go slurry, you are done with this position.",
        "<strong>Time.</strong> Even a “comfortable” tie has a clock. Check every few minutes until you know that body in that tie.",
      ),
      h("How to put someone in"),
      ol(
        "Negotiate: wrists, ankles, arms, torso? Front or back? How long? What happens if they panic?",
        "Empty pockets. No jewellery that will bite. Hair out of clasps.",
        "Cuff loosely, then snug. You should fit two fingers. Clip, then check again because people pull.",
        "Stay where they can see or hear you. Narrate if they like that; be quiet if they like that. Do not disappear to “get a toy” without a check-in.",
        "Build the scene on top of the restraint. The first scene can just be: stay, breathe, be touched, be released.",
        "Take them out slower than you think. Blood returns. Shake-out, water, wrap.",
      ),
      h("Panic and drops"),
      p("Some people panic in restraint even when they asked for it. That is not brat. That is a nervous system. Get them out. Do not lecture. Warmth, water, a blanket, a simple true sentence: “You are out. I am here.” Talk later."),
      p("Positional asphyxia is real: face-down, chest compressed, drunk, or hogtied. If in doubt, sit them up. If they are not breathing normally, this is no longer a scene — it is first aid."),
      h("Rope, in brief"),
      ul(
        "Learn single-column and a reliable cuff before anything decorative.",
        "Keep rope off the front of the neck, and off nerves at the wrist, inner elbow, armpit, and outer knee.",
        "Natural fibre (jute, hemp) bites and holds; synthetics can slip and melt. Pick one and learn it.",
        "Never hoist a person with a tie you cannot undo under stress.",
        "Take a class. Videos are not a spotter.",
      ),
    ),
  },
  {
    key: "edu-train-brat",
    title: "How to train a bratty submissive",
    category: "education",
    subcategory: "how-to",
    sort: 40,
    body: doc(
      p("A brat is not a submissive who has failed. A brat is a submissive whose play is the test: “Will you still hold me if I push?” Training a brat is teaching them that the frame is real, the fun is welcome, and cruelty without a scene is not the game."),
      h("First, name the game"),
      p("Sit out of dynamic and write three lists together:"),
      ul(
        "<strong>In-bounds brat.</strong> Sass, loopholes, fake innocence, slow obedience, stealing the last word.",
        "<strong>Out of bounds.</strong> Real insults, hitting a hard limit, public humiliation you did not agree, ignoring a red, using the Dominant’s actual wounds as a toy.",
        "<strong>What “caught” looks like.</strong> A look, a countdown, a position, a punishment from the list, laughter and a kiss. If they do not know what winning-at-losing feels like, they will escalate until someone is actually hurt.",
      ),
      h("The frame"),
      ol(
        "<strong>Rules in writing.</strong> Few, clear, enforceable. “Be respectful in front of other people” is a rule. “Never sass me” is a war with a brat.",
        "<strong>Consequences that match.</strong> Playful push, playful catch. Mean push, real stop. Do not punish with a hard limit. Do not invent a new humiliation in anger.",
        "<strong>Follow through.</strong> A brat who is never caught learns that the Dominant is theatre. A brat who is always crushed learns to go quiet, not to submit.",
        "<strong>Praise the landing.</strong> When they finally kneel, or say it straight, mark that louder than the chase. Brats often starve for the moment they can stop performing.",
      ),
      h("How to catch without becoming the villain"),
      ul(
        "Keep your voice even. If you are actually angry, pause the dynamic. Anger is not a taming tool.",
        "Name the behaviour, not the person. “That rule still stands” lands. “You are impossible” becomes a wound.",
        "Offer the out you both agreed: position, count, written lines, a task, loss of a privilege you actually control.",
        "If they safeword, they have won at safety. Thank them. Never add a punishment for the word.",
        "Debrief bratting the way you debrief a scene. What was hot. What was too much. What to try next time.",
      ),
      h("Training over time"),
      p("Pick one protocol to install at a time — a title, a morning check-in, a kneeling greeting. Let them brat around it. Catch them. Repeat until the ritual is easy. Then add the next. A brat who is “trained” overnight has usually just gone numb."),
      p("Give them jobs that use the brat: loophole hunting in a contract draft, choosing the next game, writing a worse version of a rule so you can both laugh and then set the real one. Use the spark. Do not try to extinguish it and keep the person."),
      p("Read <em>How to become a good brat tamer</em> if you are the one holding the frame, and the bratting activities when you want to practise rather than read."),
    ),
  },
  {
    key: "edu-brat-tamer",
    title: "How to become a good brat tamer",
    category: "education",
    subcategory: "how-to",
    sort: 50,
    body: doc(
      p("Taming is not breaking. A good tamer is steady, amused, and impossible to top from a tantrum. You are the wall they get to throw themselves at because the wall does not crumble and does not hit back for real."),
      h("The job"),
      ul(
        "Hold the agreed rules when it would be easier to laugh it off or explode.",
        "Keep the play in the playground. When it leaves the playground, you stop being a tamer and become a partner having a fight — which you should have as partners, not as roles.",
        "Give the brat a worthy opponent. Cleverness on their side deserves craft on yours, not volume.",
        "Let them feel caught, contained, and still wanted.",
      ),
      h("Skills to build"),
      ol(
        "<strong>A still face.</strong> Practise not taking the bait for three breaths. Then answer.",
        "<strong>A small menu of catches.</strong> One look, one position, one punishment, one reward for coming back in. You should be able to run them when you are tired.",
        "<strong>Humour without contempt.</strong> You can find them ridiculous and delicious. You may not find them worthless.",
        "<strong>Repair.</strong> After a hard catch, you are the one who opens the door: water, a hand, “Come here.” If you only ever win, they will stop playing.",
        "<strong>Self-knowledge.</strong> If bratting hits your shame, your need to be obeyed at all times, or your temper, say so. Either renegotiate the kink or get support. Do not make them pay for your unexamined pride.",
      ),
      h("What good tamers do not do"),
      ul(
        "Do not use real-life necessities as leverage (food, sleep, work, medication, the relationship itself).",
        "Do not stack punishments because you lost the beat.",
        "Do not mock a drop or a safeword.",
        "Do not train by isolation or silent treatment unless that was explicitly negotiated as play, with a time cap and a check-in.",
        "Do not compete with them for who can be crueller. You will win, and you will lose them.",
      ),
      h("A simple tamer’s loop"),
      p("See the push. Name it. Offer the known consequence. Follow through. Receive them when they yield. Praise the yield. Reset the warmth. If you skip the last two, you are just punishing."),
    ),
  },
  {
    key: "edu-good-dom",
    title: "How to be a good Dominant",
    category: "education",
    subcategory: "how-to",
    sort: 60,
    body: doc(
      p("Dominance is a service with a spine. You take responsibility for the frame, the scene, and the person who handed you power. The aesthetic is optional. The responsibility is not."),
      h("The work, not the costume"),
      ul(
        "<strong>Listen harder than you speak.</strong> Their limits, drop patterns, and ordinary day are your actual brief.",
        "<strong>Decide, then check.</strong> A Dominant who never decides is a roommate in leather. A Dominant who never checks is a risk.",
        "<strong>Be consistent.</strong> Rules you forget are not rules. If you cannot enforce it this month, take it off the list.",
        "<strong>Stay sober enough to run the room.</strong> If you cannot drive, you cannot run edge play.",
        "<strong>Repair.</strong> You will get it wrong. A good Dominant notices, owns it without collapsing, and makes the next round safer. Ego is not a sacrament.",
      ),
      h("Before you take power"),
      ol(
        "Know your own yes, no, and need. A Dominant with unsaid needs will take them out of the submissive’s hide.",
        "Negotiate when you are both clothed and fed. Write it. Dates, safewords, aftercare, who can pause the dynamic.",
        "Learn basic first aid for the play you actually do. Know when a mark is a bruise and when it is a problem.",
        "Have a life. A Dominant whose only self is the role will smother the person in it.",
      ),
      h("In scene"),
      ul(
        "Start below the fantasy. Warm the body and the trust.",
        "Watch breath, skin, eyes, and the way they stop using words. Topspace is real; so is missing a safeword because you were performing.",
        "Give instructions one at a time unless they are trained for stacks.",
        "End on purpose. A scene that fizzles because you got tired is a drop waiting to happen. Close it: words, water, hands, what happens next.",
      ),
      h("Out of scene"),
      p("Be someone they can bring a boring problem to. Pay attention to sleep, food, and whether the dynamic is covering for a fight you will not have. Do not hide behind “because I said so” when the question is rent, family, or a limit."),
      p("Pride in the role looks like this: they are more themselves with you, not less. They take risks you have earned. They tell you the truth. If they only ever perform for you, you are being fed, not followed."),
    ),
  },
  {
    key: "edu-good-sub",
    title: "How to be a good submissive",
    category: "education",
    subcategory: "how-to",
    sort: 70,
    body: doc(
      p("Submission is not disappearance. It is a skilled choice: you offer power, you keep a spine, and you tell the truth soon enough that your Dominant can actually lead."),
      h("The craft"),
      ul(
        "<strong>Know your limits before you are high on the scene.</strong> Hard nos, soft nos, curiosities. Update them. You are allowed to grow stricter.",
        "<strong>Safeword without a speech.</strong> The word is a tool, not a failure. Using it is obedience to the real rule.",
        "<strong>Receive.</strong> Let praise land. Let a hand land. You cannot be led if you are already three steps into what you think they wanted.",
        "<strong>Do the boring parts.</strong> Check-ins, hydration, stretching, writing the journal page. Fantasy sits on maintenance.",
        "<strong>Do not make them guess.</strong> “Green, I want more of that” is gold. Suffering in silence and exploding later is not devotion, it is a trap.",
      ),
      h("Service that actually serves"),
      p("Ask what would help this week — not what looks like service in a story. Sometimes it is kneeling. Sometimes it is doing the thing they hate doing. Match the gift to the person, not to your favourite ritual."),
      h("Subspace, drop, and pride"),
      p("Subspace can make you agree to things you would not agree to in daylight. Negotiate before. Confirm after. If you drop — shame, ache, insomnia, a sudden no — say so. Drop is chemistry and meaning, not evidence you are bad at this."),
      p("Pride in the role looks like this: you can kneel without hating yourself, and stand without the dynamic collapsing. You can brat or serve according to the agreed game. You can say “that hurt wrong” and still be theirs."),
      h("What is not required"),
      ul(
        "Pain you did not consent to.",
        "A personality wipe.",
        "Always being ready.",
        "Protecting their ego from your limits.",
        "Taking care of their aftercare instead of your own — unless that is the negotiated service, and you still get yours.",
      ),
    ),
  },
  {
    key: "edu-aftercare",
    title: "Aftercare",
    category: "education",
    subcategory: "how-to",
    sort: 75,
    body: doc(
      p("Aftercare is what you do on purpose once the scene, the ritual, or the high is over. It is how you land a nervous system you took up into the air. It is not a cute extra. It is part of the scene, and it starts when you close the play — not when you feel like being nice again."),
      callout("If you can run the intensity, you can run the landing. A Dominant who disappears into a shower, a phone, or sleep while they are still shaking is not “done.” They are unfinished."),
      h("What it is"),
      p("During play, bodies dump adrenaline, endorphins, oxytocin, sometimes tears, sometimes nothing obvious. Aftercare is the sequence that tells their body: you are here, you are safe, the story is over, I am still with you. It can be quiet. It can be filthy and then gentle. It can be five minutes of water and a blanket. It is whatever you both named as the way back."),
      ul(
        "<strong>Physical.</strong> Water, sugar, a wee, warmth, a wash, arnica, clothes, food they can actually eat.",
        "<strong>Emotional.</strong> A voice. Praise that is specific. Permission to cry, to joke, to say nothing. Being held or being given space — they are not the same person every night.",
        "<strong>Practical.</strong> Toys out, ropes off, marks checked, a towel, who sleeps where, a plan for work in the morning.",
        "<strong>The next day.</strong> A message, a meal, a boring check-in. Drop often arrives late. Aftercare is not only the sofa.",
      ),
      h("Why it matters"),
      ul(
        "Play without a landing teaches their body that intensity is abandonment. They will either stop going deep, or they will go deep and crash when you are not looking.",
        "Aftercare is how you prove the power was given, not taken. It is the receipt.",
        "You will miss a cue someday. Aftercare is the net under that miss.",
        "Shame, marks, a word that landed too well, an orgasm they did not expect — all of it needs a place to go that is not a 3am spiral.",
        "Your own drop is real too. Landing them does not replace landing yourself. Do both. See <em>Domspace</em>.",
      ),
      h("What it is not"),
      ul(
        "A reward they can lose for bratting. Aftercare is not a treat. It is first aid for a state you helped create.",
        "An interrogation. Debrief when they can think. Not while they are still in subspace.",
        "Sex they did not ask for, piled on because you are still hard. Ask. “Do you want more, or do you want still?”",
        "A script you copy from the internet if it does not fit this person. Some people need quiet. Some need a running commentary. Some need to be left in the room with the door open and a glass of water.",
      ),
      h("How to give it"),
      ol(
        "<strong>Close the scene out loud.</strong> A sentence they know: “Scene over. You did well. I have you.” Unbind. Ungag. Colours still work.",
        "<strong>Look at the body.</strong> Circulation, cuts, nausea, cold, whether they can stand. Treat what you see before you chase a mood.",
        "<strong>Offer, do not pile on.</strong> Water. A blanket. Your chest or a bit of space. One thing at a time. Watch which one they take.",
        "<strong>Keep talking if they need a voice.</strong> Simple, specific: what you liked, that they are safe, what happens next (shower, bed, food). Do not make them perform gratitude.",
        "<strong>Keep quiet if they need quiet.</strong> A hand on a nape can be the whole paragraph.",
        "<strong>Get sugar and salt in.</strong> Juice, chocolate, toast, an electrolyte. Intensity burns through people who “are not hungry.”",
        "<strong>Wash and mark-check together if that is your way.</strong> A shower can be aftercare. It can also be too much sensation. Ask.",
        "<strong>Stay reachable.</strong> If you must leave the room, say when you will be back, and be back. A brat who jokes “go on then” may still panic if you vanish.",
        "<strong>Write the next-day check-in before you sleep.</strong> A time, a medium, a question: “How is your head? Any marks that worry you? Anything you want off the table next time?”",
      ),
      h("Matching the person, not the fantasy"),
      ul(
        "<strong>The floaty one.</strong> Slow voice, warmth, do not quiz them. They may agree to anything. Do not add new play.",
        "<strong>The shaky one.</strong> Ground: name, date, room, water, feet on the floor.",
        "<strong>The one who goes sharp or mean.</strong> That can be drop wearing armour. Do not punish the landing. Offer food and a later talk.",
        "<strong>The brat.</strong> They may sass instead of asking to be held. Catch the sass lightly if that is your game, then give the care anyway. Do not make them earn the blanket.",
        "<strong>The one who wants space.</strong> Space with a tether: “I will be in the kitchen. Text if you want me.” Check at the time you said.",
        "<strong>Heavy pain, humiliation, or CNC.</strong> Plan aftercare before the scene. Include a re-entry sentence that takes the fiction off: who you both are, that the words were play, that they are wanted.",
      ),
      h("A small kit"),
      p("Water, a snack they actually like, a towel, a soft layer, their favourite blanket, pain relief you have already agreed is allowed, a charger, tissues, a spare pair of underwear, the aftercare note you wrote on a non-horny day. Keep it where you play. Future-you is worse at shopping."),
      p("Read <em>Subspace</em> and <em>Domspace</em> with this. Aftercare is how both of those states come home."),
    ),
  },
  {
    key: "edu-subspace",
    title: "Subspace",
    category: "education",
    subcategory: "how-to",
    sort: 76,
    body: doc(
      p("Subspace is a shift in their nervous system during or after play: the world narrows, words get expensive, time smears, and the Dominant's voice can feel like the only solid thing in the room. It is not a trophy. It is a state. Some nights they go there in ten minutes. Some nights they never leave the shoreline, and that is still a good scene."),
      callout("A person in subspace can look like they are saying yes to everything. Treat that as a yellow you have not heard yet. Do not add new acts, new degradation, or extra time because they went quiet and pretty."),
      h("What it is"),
      p("Bodies under intense sensation, focus, trust, or ritual dump chemicals that change pain, fear, and self-talk. For some people that feels like floating. For others it is heavy, small, animal, tearful, or blank. Service, impact, bondage, voice, orgasm control, even a long kneel can open the door. It is not always sexual. It is not always bliss. It is a trance you are responsible for because you helped build it."),
      h("How it can feel — to them"),
      ul(
        "Warm, floaty, far away, as if the room is underwater.",
        "Very small, very good, very simple. Decisions feel impossible and that is the point.",
        "Wordless. They know they should speak and the sentence will not form.",
        "High pain tolerance that is a trick, not a superpower. They can be injured without the usual alarm.",
        "Time gone. A twenty-minute scene felt like two, or two hours felt like a breath.",
        "Tears without a sad story. Laughter that is not a joke. Shaking that is not cold.",
        "A fierce need to please, or a fierce need to be still and used, or both.",
        "Nothing cinematic at all — just quiet, heavy limbs, and a brain that has stepped aside. Believe them if they say they were “in it” without the porn face.",
      ),
      h("Signs to look for"),
      ul(
        "<strong>Eyes.</strong> Soft, slow to track, glassy, or locked on you and not much else.",
        "<strong>Voice.</strong> Smaller, later, slurred, one-word answers, or gone. A brat's smirk going still is a sign, not a win you stack more sass on.",
        "<strong>Breath.</strong> Deep and even, or high and forgotten. Remind them to breathe.",
        "<strong>Body.</strong> Heavy, pliant, delayed flinch, less bracing than they showed in warm-up.",
        "<strong>Colours.</strong> They stop offering green on their own. You have to ask. If they cannot answer, you ease off or stop.",
        "<strong>The tell they named.</strong> A hand going slack, a particular sound, a stare. Write it in Notes. Do not guess every time.",
        "<strong>What is not a sign.</strong> Endurance. Faking. Freeze from fear. If the eyes go flat, the jaw locks, or they look like they are waiting for it to be over, that is not subspace. That is a stop.",
      ),
      h("How to take them there"),
      p("You cannot force subspace. You can make the conditions honest enough that their body will consider it."),
      ol(
        "Negotiate first, while they can still think. Subspace is a terrible time to invent the scene.",
        "Start below the fantasy. Warm skin, warm trust, a rhythm they can predict. Surprise is for later, if they asked for it.",
        "Pick one door: impact with a build, bondage and stillness, service and repetition, voice and praise, a long hold. Mixing five kinks is noise.",
        "Be consistent. Same cue, same cadence, same hand. The nervous system drops when it knows who is driving.",
        "Watch more than you perform. If you are chasing a look for your own pride, you will miss the yellow.",
        "Use the voice they trained to. Quiet and sure lands more people than a speech.",
        "Give them something to do with the mind: count, hold a position, repeat a phrase, breathe on your count. Busy brains do not drop. Occupied ones sometimes do.",
        "Do not clock it. Asking “are you in subspace yet?” yanks them out. Ask colours. Ask breath. Ask one yes/no.",
        "For a brat: catch them, then settle. A brat who is still hunting cannot drop. End the game on purpose, then give the rhythm.",
      ),
      h("While they are in it"),
      ul(
        "Stay. A body in subspace left alone can drop into panic.",
        "Keep stimulation inside what you already agreed. Depth is not permission.",
        "Check in in a way they can answer: squeeze, tap, “colour.” If you get nothing useful, you come down.",
        "Track time, temperature, circulation, and whether they have gone too still.",
        "End on purpose before they crash. Bring them back with your voice, their name, water, sitting up slowly.",
      ),
      h("Subdrop"),
      p("Subdrop is the come-down: hours or a day or three later, the chemicals leave and meaning rushes in. It can look like sadness with no story, shame, clinginess, numbness, a sudden “I am bad at this,” insomnia, a short temper, or a brat who is only actually scared. It is not proof the scene was wrong. It is proof a body did something large."),
      ul(
        "<strong>When.</strong> Same night, next morning, or a delayed Tuesday. Heavy scenes and new intensity drop harder. So do scenes that ended without a close.",
        "<strong>What helps.</strong> The aftercare you already planned, food, sleep, daylight, a boring check-in, less protocol for a day if they need to be a person, more protocol if they need the frame. Ask which. Do not guess from your own drop.",
        "<strong>What does not help.</strong> “Cheer up.” A surprise scene to “fix” them. Silence because you feel awkward. Making them explain the chemistry as a moral essay.",
        "<strong>When it is more than drop.</strong> If they cannot eat, cannot work, cannot be touched, or the shame is about a real wound you used, you stop play and deal with the person. Drop is not a licence to wait it out if they are in trouble.",
      ),
      h("Aftercare this state requires"),
      ol(
        "A spoken close. Name, time, “the scene is over.”",
        "Warmth, water, sugar, a slow sit-up. They may be cold and not know it.",
        "Do not leave them in bondage or a corner to “soak.” Soaking is a negotiated beat with you in the room.",
        "Re-enter who they are: partner, name, what is true outside the fiction.",
        "A next-day message even if they said they were fine on the sofa. Especially then.",
        "If drop shows: more of the same, not a new intensity. Offer a walk, a meal, a quiet evening. Keep colours available.",
      ),
      p("Read <em>Aftercare</em> for the practical kit, and <em>Domspace</em> so you do not miss your own landing while you are watching theirs."),
    ),
  },
  {
    key: "edu-domspace",
    title: "Domspace",
    category: "education",
    subcategory: "how-to",
    sort: 77,
    body: doc(
      p("Domspace — also called topspace — is the shift on your side of the rope. The room gets simple. Time stretches. Their breath, their skin, the next decision: that is the whole job. It can feel like a clean hunt, like tender authority, like a quiet that is louder than the impact. It is not an excuse. It is a state you have to come back from on purpose."),
      callout("If subspace makes them agree too easily, domspace can make you miss a yellow. Build checks into the scene that do not depend on you feeling like a god."),
      h("What it is"),
      p("You are running attention, risk, and another person's nervous system. When that focus locks, your own chemistry moves: adrenaline, focus, sometimes a high that is sexual, sometimes one that is not. The ego wants to call it power. The work is still care. Domspace is the flow state of doing that work well — and the tunnel vision of doing it too hard."),
      h("How it can feel"),
      ul(
        "Sharp and quiet. Fewer thoughts. The next stroke, the next sentence, the next pause.",
        "Larger than your day-self. Voice drops. Hands know. The performance falls off and something plainer takes over.",
        "Protective and predatory in the same breath, if that is your flavour. Wanting to ruin them and wrap them.",
        "Time gone. You meant twenty minutes and the clock says an hour.",
        "A hum in the chest, a stillness in the jaw, heat, an erection that is not the point, or no sexual charge at all — only the work.",
        "Irritation at interruption: a phone, a giggle, a brat loop. That irritation is data. It can mean “hold the frame.” It can mean “you are getting too high to be kind.” Know which.",
        "After, either a clean tiredness or a crash: emptiness, guilt, restlessness, a need to be alone, a need to be held. That is drop, not proof you are a monster or a fraud.",
      ),
      h("Signs you are in it"),
      ul(
        "You are watching them more than you are watching yourself in the fantasy.",
        "Instructions come out shorter. You are not narrating a novel.",
        "You can feel the next beat before you decide it.",
        "Peripheral noise falls away. This is useful until you stop hearing the kettle, the colour, or the clock.",
        "You do not want to stop. That is the dangerous one. Wanting to continue is not the same as it being wise.",
        "A brat can pull you out or push you deeper. If their sass makes you actually angry, you are leaving domspace and entering a fight. Pause.",
      ),
      h("How to get there"),
      ol(
        "Do the unsexy work first. Negotiation, water, toys laid out, a clock you can see, aftercare kit in reach. A brain that is scrambling for lube does not drop into authority. It fusses.",
        "A threshold ritual: a collar, a sentence, a kneel, you washing your hands. Same door each time so your body knows the room has changed.",
        "Start below the peak. Warm them, and warm your own attention. Domspace arrives through doing the job, not through putting on a voice in the bathroom mirror.",
        "Reduce inputs. Phone out. One scene, one flavour. You cannot get into the quiet if you are also performing for an imaginary audience.",
        "Breathe on a count. Plant your feet. Feel your hands. Dominance is a body, not a TED talk.",
        "Let yourself care. Cold for show is a costume. Many people drop into domspace when they stop trying to look Dominant and start tracking the person in front of them.",
        "If you are tired, hungry, furious, or drunk, you will not find the good version. You will find sloppy power. Reschedule.",
      ),
      h("Signs to watch — in you, and in them"),
      ul(
        "<strong>Green-enough.</strong> They are with you, colours work, breath is usable.",
        "<strong>Too far in you.</strong> You skip a colour check because you “can tell.” You add one more cane strike because the rhythm is pretty. You hate the idea of stopping. Ease off or call the close.",
        "<strong>Too far in them.</strong> See <em>Subspace</em>. Your job in domspace is to notice theirs.",
        "<strong>The miss.</strong> You feel nothing, or you feel only panic. Not every scene will give you the high. Do not punish them for a night your chemistry stayed home. Run a smaller scene well.",
      ),
      h("Coming down — Dom drop"),
      p("When the focus breaks, some Dominants feel hollow, ashamed of what they enjoyed, buzzing and unable to sleep, or suddenly small. You may want to flee the person you were just inside a scene with. That is chemistry plus meaning. It is common. It is your job to plan for it so they do not experience your drop as rejection."),
      ul(
        "<strong>What it can look like.</strong> Guilt (“I hurt them”), numbness, a crash after the erection goes, irritability, needing silence, needing praise you feel you cannot ask for, a day of “I am not cut out for this.”",
        "<strong>What they may see.</strong> You going quiet, going practical, going to your phone, going sharp. Name it if you can: “I am dropping. I am here. I need a minute, then I will take care of you.”",
      ),
      h("Aftercare when you leave domspace"),
      ol(
        "<strong>Close them first if they still need you.</strong> Water, unbind, the spoken end, a blanket. Your drop does not get to skip their landing. If you cannot do both, say so and do the physical safety, then sit.",
        "<strong>Then land yourself.</strong> Water, food, a shower, clothes, the room put back. A walk. Sleep. You are an animal too.",
        "<strong>Ask for what you need without making them parent you mid-drop.</strong> If you need to be held, say “hold me.” If you need ten minutes alone, give them a time and a way to reach you, and do not make them guess whether they failed.",
        "<strong>A sentence that puts the power down.</strong> Out of role, you are partners. They should not have to keep submitting to keep you stable.",
        "<strong>Debrief later.</strong> What you enjoyed, what you almost missed, whether you got too high. The next day is kinder than the afterglow.",
        "<strong>If they offer aftercare to you.</strong> That can be service, and it can be beautiful. It is not their job to absorb your shame. Do not unload “I am a bad person” onto the body you just beat. Get a friend, a journal, or a professional for that.",
        "<strong>The next-day check is for both of you.</strong> “How is your head?” includes yours. If you went dark, say so before they invent a story that they were too much.",
      ),
      h("What you still owe"),
      p("Domspace is not a possession that removes the safeword. It is not a reason to skip aftercare, to stack pain, or to treat a brat's landing as a nuisance. The high is a tool. The person is the point. If the state makes you crueler than the scene you negotiated, you come down. Pride is being able to stop."),
      p("Keep <em>Aftercare</em> and <em>Subspace</em> next to this. You are landing two nervous systems. Start with theirs, then do not forget yours."),
    ),
  },
  {
    key: "edu-difficult-talk",
    title: "Open communication for difficult topics",
    category: "education",
    subcategory: "how-to",
    sort: 80,
    body: doc(
      p("The hard talks are the ones that keep the rest of this from turning into theatre. Sex, jealousy, a limit that moved, a scene that went wrong, money, health, “I do not want this flavour any more.” You will have them, or you will have a blow-up wearing a collar."),
      h("Set the room"),
      ul(
        "Not in scene. Not in the last five minutes before sleep, unless someone is unsafe.",
        "Phones down. Sit at the same height. Water on the table.",
        "Time-box it (thirty to forty minutes) with permission to pause and return tomorrow. An endless talk is another way to flee.",
        "If you use honorifics, decide whether this talk is in-dynamic or out. Most difficult topics need out.",
      ),
      h("A script that does not start a war"),
      ol(
        "<strong>Ask for the talk.</strong> “I need twenty minutes on something tender. Tonight or tomorrow?” Surprise ambush makes people stupid.",
        "<strong>One topic.</strong> Not a year of evidence. You can stack later if the first one goes well.",
        "<strong>Speak in first person and present tense.</strong> “I dropped after Thursday and I have been scared to kneel” is usable. “You always” is a summons to court.",
        "<strong>Say the need under the complaint.</strong> “I need a slower warm-up” is a request. “You do not care” is a verdict.",
        "<strong>The other person reflects.</strong> “What I heard is… Did I get it?” Until they have it, do not argue.",
        "<strong>Make one small agreement.</strong> A change you can see in seven days. Write it in Notes if it is a rule.",
        "<strong>Close.</strong> A hand, a sentence of appreciation for the honesty, and a real aftercare plan if the topic was a scene.",
      ),
      h("Topics that deserve this treatment"),
      ul(
        "A limit that got brushed.",
        "A punishment that felt like contempt.",
        "Wanting more, or less, power exchange in ordinary life.",
        "Jealousy, other partners, time.",
        "Health, pain, medication, mental health weeks.",
        "The dynamic covering for a fight about chores, money, or respect.",
        "I think I am a switch. I think I am not a brat. I think I want a collar. I think I want it off.",
      ),
      h("When it is going badly"),
      p("If voices rise, call a pause. Twenty minutes apart, then back, or tomorrow. If you are using the other person’s wounds as ammunition, you are done for the day. If someone is scared, stop the topic and get to safety — physical or emotional. Repair is a different conversation from decision-making."),
      p("Use the Talk page for lighter daily questions. Use this note when the thing in your chest has a name and a cost."),
    ),
  },
  {
    key: "edu-instructions",
    title: "How to give better instructions",
    category: "education",
    subcategory: "how-to",
    sort: 90,
    body: doc(
      p("Bad instructions create brats by accident, drops by confusion, and Dominant frustration that looks like the submissive’s fault. A good instruction is a kindness: it can be obeyed."),
      h("The shape of an instruction that works"),
      ol(
        "<strong>One action.</strong> “Kneel here, hands on thighs, eyes down.” Not five rituals in one breath unless they are trained for that stack.",
        "<strong>A place and a posture.</strong> Vague “behave” cannot be completed. Concrete “wait in present until I touch your shoulder” can.",
        "<strong>A finish line.</strong> Time, a count, a word you will say, or “until I release you.” Open-ended orders need extra trust and extra check-ins.",
        "<strong>The why, when it helps.</strong> “I want your head quieter” teaches. “Because I said so” is for when the why is already known.",
        "<strong>How they tell you it is done, or too much.</strong> “Say ‘set’ when you are there.” “Safeword if the knee goes.”",
      ),
      h("Tone"),
      p("Match the scene. Protocol can be spare. Care can be warm. Degradation is a negotiated flavour, not the default setting for every order. If you only ever snap, they will not be able to hear you when you need to be gentle, and the other way around."),
      h("When they get it wrong"),
      ul(
        "First assume the instruction was muddy, not that they are defiant.",
        "Repeat once, shorter. Show if you can.",
        "If it is brat, catch the brat — do not rewrite the order into a riddle.",
        "If it is capacity (pain, freeze, drop), stop stacking. Get them stable. Teach later.",
      ),
      h("Written tasks"),
      p("Same rules. Title. What good looks like. When it is due. What happens if it is done, and if it is not — if you use stakes, they belong in the task, not in a surprise. Put photos or a catalogue item on it if the body needs a picture."),
      p("Practise with the exercise <em>Instruction practice</em>. Ten minutes will show you every leak in how you speak."),
    ),
  },
  {
    key: "edu-negotiate-scene",
    title: "How to negotiate a scene",
    category: "education",
    subcategory: "how-to",
    sort: 100,
    body: doc(
      p("A scene is a short story you both agree to enter. Negotiation is how you keep it a story instead of an accident. Do it before anyone is naked and buzzing, and again if the plan changes."),
      h("The skeleton"),
      ol(
        "<strong>Who is running it.</strong> Who can call yellow and red. If you switch mid-scene, say how.",
        "<strong>The want.</strong> Each person, one or two sentences. “I want to feel taken in hand and a bit overwhelmed, then held.”",
        "<strong>The flavour.</strong> Praise, degradation, protocol, primal, service, quiet, filthy talk — pick the lane.",
        "<strong>The acts.</strong> What may happen to which body parts, with which toys. What is off the table tonight even if it is usually on.",
        "<strong>Intensity and duration.</strong> A number you both understand, and a clock. You can end early. You should not run long because nobody wanted to be the one to stop.",
        "<strong>Safewords.</strong> Traffic lights work: green / yellow / red. Plus a non-verbal if anyone might be gagged or beyond words. What you will do on yellow (ease off, check) and on red (stop, release, aftercare).",
        "<strong>Aftercare.</strong> Water, food, quiet, talk, space, who sleeps where, a check-in the next day. Write it if you forget when you are floaty.",
        "<strong>Risks.</strong> Marks that must not show, work in the morning, medication, a sore knee, a bad week. The truth belongs here.",
      ),
      h("Traffic lights, in practice"),
      ul(
        "<strong>Green.</strong> More of this is welcome, or stay.",
        "<strong>Yellow.</strong> Too much, or wrong flavour, or I need a second. Do not punish a yellow.",
        "<strong>Red.</strong> Scene over. Unbind. The person who called it does not owe a performance of being fine.",
      ),
      h("A small scene is still a scene"),
      p("Ten minutes of kneeling and a wand is worth this skeleton in miniature. You are teaching your future selves how to go bigger without getting lost."),
      p("After: debrief when you have eaten. What worked, what to keep, what never again, what to try next time. Put keepers in Notes or the Journal. If something went wrong, treat it as data, not as a verdict on the relationship."),
    ),
  },
  {
    key: "edu-roleplay",
    title: "How to write and run a roleplay",
    category: "education",
    subcategory: "how-to",
    sort: 110,
    body: doc(
      p("Roleplay is a costume for a feeling. Inspector and subject, handler and pet, stranger in a hotel, captain and crew — the plot is there to give your nervous systems a script. Keep the script light enough to hold, and the safewords real."),
      h("Build the fiction"),
      ol(
        "<strong>The feeling, not the novel.</strong> “I want to be inspected and a little embarrassed” is a brief. A twelve-page backstory is homework nobody asked for.",
        "<strong>Names and address.</strong> What you call each other in the fiction. What is forbidden.",
        "<strong>The setting in one line.</strong> A doorway, a chair, a hotel lamp. You do not need a set. You need a threshold: a sentence that starts the play and a sentence that ends it.",
        "<strong>Who knows what.</strong> Are you strangers in the fiction? Is one of you in on a secret? CNC-flavoured roleplay needs extra care — the fiction of no consent is never actual no consent.",
        "<strong>Props from the Catalogue.</strong> One or two. A collar, a clipboard, a toy. Too many props become a fumble.",
        "<strong>The beat sheet.</strong> Arrival. Tension. Peak. Landing. Aftercare out of character.",
      ),
      h("Running it"),
      ul(
        "Start with the threshold line, not with a joke about feeling silly. You can laugh after.",
        "If someone corpses (breaks into giggles), you can either fold it in or pause, breathe, restart from the last beat.",
        "Stay inside the negotiated acts. A role is not a blank cheque to try a new kink “in character.”",
        "End with the closing line, then a clear “scene over” so the fiction does not leak into a fight about dishes.",
      ),
      h("When roleplay hurts wrong"),
      p("If the character uses a real slur you did not agree, or a real memory, call yellow or red. Out of character, name it. Either rewrite the role or retire it. A good partner would rather lose a scene than win a wound."),
      p("There is an activity under Activities — <em>Create a roleplay</em> — that walks you through a one-page script you can keep in the Roleplay page."),
    ),
  },
  {
    key: "ex-confidence",
    title: "Confidence in your role",
    category: "exercises",
    subcategory: "self",
    sort: 10,
    body: doc(
      p("Time: 20 minutes, alone. Then 10 minutes with your partner if you want. You are training the feeling of occupying the role without performing a cartoon of it."),
      h("Alone"),
      ol(
        "Stand or sit how you sit when you are actually in the role — not the Pinterest version. Notice jaw, shoulders, breath, where your eyes go.",
        "Say, out loud, one sentence that is true in the role. Dominant example: “I can take this slowly and still be in charge.” Submissive example: “I can kneel and still have a no.” Brat example: “I can push and still come back.”",
        "Write five lines: what you fear you look like in the role, and five: what you actually offer. Compare. Keep one sentence from the second list in your phone for a week.",
        "Do one tiny in-role act today with no audience: a posture, a journal line, laying out a toy, sending a single clear instruction or a single honest check-in.",
      ),
      h("Optional, together"),
      p("Each of you reads one fear and one offer. The other person answers only: “I believe this part.” No fixing. Stop there."),
      h("Debrief"),
      p("What felt like costume? What felt like you? Put one keeper in the Journal."),
    ),
  },
  {
    key: "ex-improve-self",
    title: "A week of becoming sharper",
    category: "exercises",
    subcategory: "self",
    sort: 20,
    body: doc(
      p("Time: 10 minutes a day for seven days. Pick a role you actually live, not a fantasy week you will abandon on Tuesday."),
      h("Choose one track"),
      ul(
        "<strong>Body.</strong> Sleep, water, a stretch before play, no scene on a night you skipped food.",
        "<strong>Attention.</strong> One undistracted check-in a day. Phone down.",
        "<strong>Craft.</strong> Read one Education note, or practise one instruction, or one piece of service, slowly.",
        "<strong>Nerve.</strong> One true sentence a day you have been decorating instead of saying.",
      ),
      h("Each day"),
      ol(
        "Do the small thing.",
        "Write one line: what you did, and how your body felt after.",
        "Do not add a second track until the week is done.",
      ),
      h("Day seven"),
      p("Read the seven lines to your partner, or only to yourself. Keep one habit. Drop the martyrdom. If you missed days, that is data about load, not proof you are undominant or unsubmissive."),
    ),
  },
  {
    key: "ex-know-partner",
    title: "Learn your partner",
    category: "exercises",
    subcategory: "partner",
    sort: 30,
    body: doc(
      p("Time: 40 minutes. You are not fixing them. You are collecting a better brief."),
      h("Setup"),
      p("Sit facing. One speaks, one writes. Then swap. No advice until both have spoken."),
      h("Ask these, slowly"),
      ol(
        "When do you feel most taken care of by me, in or out of dynamic?",
        "When do you feel most missed by me?",
        "What does a good order (or a good offer of service) sound like in your body?",
        "What should I never use against you, even in play?",
        "How do you want me to bring you back from brat, subspace, or topspace?",
        "What is a small thing I could do this week that would feel like I studied you?",
      ),
      h("Then"),
      p("Each of you picks one thing to do in the next seven days. Put it in Tasks or Habits if it should repeat. Do not pick five. Competence beats a manifesto."),
    ),
  },
  {
    key: "ex-dynamic",
    title: "Strengthen the dynamic",
    category: "exercises",
    subcategory: "dynamic",
    sort: 40,
    body: doc(
      p("Time: 45 minutes. Out of scene. This is a maintenance bay, not a trial."),
      h("Part one — inventory (15 min)"),
      p("Separately, write:"),
      ul(
        "What in the dynamic is giving us life right now.",
        "What has gone theatrical or stale.",
        "What we are using the dynamic to avoid (chores, sex, a fight, loneliness).",
        "One ritual worth keeping. One rule worth retiring. One we might add.",
      ),
      h("Part two — compare (20 min)"),
      p("Read them aloud. No defence for the first pass. Circle overlaps. Those are your real dynamic. The rest is optional costume."),
      h("Part three — one change (10 min)"),
      p("Agree a single change for the next two weeks. Examples: a morning honorific, a Sunday negotiation, a week off punishments, a weekly scene night, a no-phone kneel. Put it in Notes under Rules or Agreements. Diary a date to review."),
      h("Close"),
      p("A small in-dynamic beat you both like — a kiss, a kneel, a hand in the hair — then ordinary evening. The point is that the frame can bend without breaking."),
    ),
  },
  {
    key: "ex-explore-kink",
    title: "Explore a kink together",
    category: "exercises",
    subcategory: "kinks",
    sort: 50,
    body: doc(
      p("Time: 60–90 minutes including aftercare. Pick one item from <em>A map of kinks</em> that is a curious yes for both of you. If it is a yes for only one, stop — this exercise is for shared curiosity, not persuasion."),
      h("Before"),
      ol(
        "Each write: the fantasy in three sentences, the fear in one, the hard nos for tonight.",
        "Build a tiny version. Impact becomes ten warm hand spanks. Bondage becomes cuffs for five minutes. Degradation becomes one agreed phrase. CNC is not a “tiny version” for a first try — pick another door.",
        "Set safewords. Set aftercare. Set a clock.",
      ),
      h("During"),
      p("Run only the tiny version. The Dominant (or the person driving) checks yellow/green once at the midpoint. Nobody “just adds” a toy."),
      h("After, the same evening"),
      p("Water. The aftercare you booked. Then three words each: keep / tweak / never."),
      h("The next day"),
      p("A message or a sit-down: still yes, still no, want a slightly larger version, or file it. Put the keeper in Scenes or Notes so you do not rely on afterglow memory."),
    ),
  },
  {
    key: "ex-communication",
    title: "Communication skills lab",
    category: "exercises",
    subcategory: "communication",
    sort: 60,
    body: doc(
      p("Time: 25 minutes. You are drilling the muscles from <em>Open communication for difficult topics</em> on a low-stakes subject first."),
      h("Round one — reflect (8 min)"),
      p("Person A talks for two minutes about something mild (a scene they liked, a brat moment, a want). Person B may only reflect: “What I heard… What I think you need…” A corrects until it is right. Swap."),
      h("Round two — request (8 min)"),
      p("Each makes one request in the form: <em>When X, I feel Y, I need Z (a specific behaviour).</em> The other person can say yes, no, or a counter-offer. No explaining the no until the requester says they can hear it."),
      h("Round three — repair (5 min)"),
      p("Each names one moment in the last month they wish they had handled better. One sentence of ownership. One sentence of what they will try next time. No cross-examination."),
      h("Close"),
      p("Something easy and kind. If this lab surfaces a real fight, book the difficult-topics structure for another hour. Do not finish a war inside a drill."),
    ),
  },
  {
    key: "ex-instructions",
    title: "Instruction practice",
    category: "exercises",
    subcategory: "communication",
    sort: 70,
    body: doc(
      p("Time: 15 minutes. Dominant (or the person giving) speaks. Submissive (or the person receiving) obeys only what was actually said — no mind-reading, no helpful extras. Then swap if you switch."),
      h("The giver"),
      ol(
        "Give three instructions, one at a time: a posture, a simple fetch or placement, a timed hold (use the Games timer if you want).",
        "After each, ask: “What did you hear?” If it does not match, that is your sentence, not their defiance.",
        "Rewrite shorter. Try again.",
      ),
      h("The receiver"),
      ol(
        "Do exactly the instruction. If it is incomplete, you may ask one clarifying question. You may not improve it.",
        "If you want to brat, save it for a named brat round at the end — otherwise you will not learn the difference between a muddy order and a game.",
      ),
      h("Debrief"),
      p("Which instruction was easy to inhabit? Which one needed a picture, a demonstration, or a finish line? Steal that pattern for Tasks and Training."),
    ),
  },
  {
    key: "ex-create-scene",
    title: "Create a scene",
    category: "exercises",
    subcategory: "play",
    sort: 80,
    body: doc(
      p("Time: 35 minutes to design, another evening to run it. You will leave with a one-page scene you can paste into the Scenes page."),
      h("Fill this in together"),
      ol(
        "<strong>Title.</strong>",
        "<strong>Feeling we want.</strong> Two words each.",
        "<strong>Who leads.</strong>",
        "<strong>Opening image.</strong> One sentence (a doorway, a command, a piece of clothing).",
        "<strong>Allowed acts.</strong> A short list. Be vulgar if that is accurate. Be specific about body parts and toys.",
        "<strong>Forbidden tonight.</strong>",
        "<strong>Intensity.</strong> 1–5 and what that means for you.",
        "<strong>Duration.</strong>",
        "<strong>Safewords and non-verbal.</strong>",
        "<strong>Aftercare.</strong> Who does what.",
        "<strong>Marks / work / sleep constraints.</strong>",
        "<strong>Closing image.</strong> How we will know it is over.",
      ),
      h("Then"),
      p("Do not run it the same hour you design it unless it is very small. Let it sit. If either of you wants a change, the change happens before anyone is in subspace."),
      p("After you run it, add a debrief line to the scene note: keep / tweak / never. Completing it in Scenes is optional; the learning is not."),
    ),
  },
  {
    key: "ex-create-roleplay",
    title: "Create a roleplay",
    category: "exercises",
    subcategory: "play",
    sort: 90,
    body: doc(
      p("Time: 30 minutes to write, later to play. Keep it to one page. If it needs a novel, it is not ready to be inhabited."),
      h("The page"),
      ol(
        "<strong>Working title.</strong>",
        "<strong>The feeling.</strong> (Inspected, hunted, useful, adored, ruined — pick one primary.)",
        "<strong>Roles and names.</strong>",
        "<strong>Threshold line</strong> that starts the fiction.",
        "<strong>Setting in one line.</strong>",
        "<strong>Three beats.</strong> Arrival, peak, landing.",
        "<strong>Props.</strong> One or two from the Catalogue, or none.",
        "<strong>Lines that are in.</strong> A few phrases you want said.",
        "<strong>Lines that are out.</strong>",
        "<strong>Safewords stay ordinary-world words.</strong> They punch through the fiction on purpose.",
        "<strong>Closing line</strong> and an out-of-character “scene over.”",
        "<strong>Aftercare.</strong>",
      ),
      h("Playtest"),
      p("Read it aloud once without acting. If you cringe at a line, cut it. Cringe in the living room becomes freeze in the scene. When you run it, you may improvise inside the beats. You may not add a new kink “because the character would.”"),
      p("Save the page under Roleplay. Use the wheel there if you want chance to pick the next fiction from the ones you have actually written."),
    ),
  },
  {
    key: "ex-role-voice",
    title: "Communication in your role",
    category: "exercises",
    subcategory: "roles",
    sort: 100,
    body: doc(
      p("Time: 20 minutes. You are finding a voice you can sustain — not a movie accent, a way of speaking that still tells the truth."),
      h("Warm-up, each of you"),
      p("Out of role, say: “I want you closer.” Then say it in role, three ways: spare, filthy, tender. Notice which one your body believes."),
      h("Drill"),
      ol(
        "The Dominant (or lead) gives a real instruction in-role, then a check-in in-role (“Colour?” “Look at me.”).",
        "The submissive (or receiver) answers in-role without hiding a yellow. Practise: “Yellow — the cuff is biting” in the same voice you use for “Yes, Sir.” The role must be able to carry bad news.",
        "Swap one piece of praise and one piece of correction. Correction aims at the act, not the person’s worth.",
      ),
      h("Brat variant"),
      p("One sassy line that is in-bounds, one catch, one sincere landing line. If the landing line is still a joke, you are not done."),
      h("Takeaway"),
      p("Write three phrases you want as standing language — a call to position, a check-in, a close. Put them in Rules or Training so you do not invent a new dialect every Thursday."),
    ),
  },
  {
    key: "ex-deal-brat",
    title: "Deal with a bratty submissive",
    category: "exercises",
    subcategory: "bratting",
    sort: 110,
    body: doc(
      p("Time: 25 minutes as a drill, not a sneak attack. You both know you are practising. Real bratting during a drill is allowed only in the marked round."),
      h("Agree the sandbox"),
      ul(
        "Two in-bounds brat moves for today (e.g. loophole, slow-walk).",
        "One catch (position, count, a known punishment).",
        "The landing (praise, touch, a simple order they will actually do).",
        "Safeword still works. So does “pause the game.”",
      ),
      h("Run three loops"),
      ol(
        "Brat pushes.",
        "Tamer names it, applies the catch without a speech.",
        "Brat yields on purpose.",
        "Tamer receives and warms. Reset.",
      ),
      h("Then talk"),
      p("Which catch felt like a game? Which one felt like a parent? Which yield was hot, and which was collapse? Adjust the menu. Put the keeper in Punishments or Training so you are not inventing consequences when you are already mad."),
      p("If anyone got actually angry, you left the sandbox. Repair as partners before you play again."),
    ),
  },
  {
    key: "ex-be-brat",
    title: "Be a bratty submissive (well)",
    category: "exercises",
    subcategory: "bratting",
    sort: 120,
    body: doc(
      p("Time: 20 minutes. Bratting is a gift if it is aimed at the game. It is a leak if it is how you say everything you are afraid to say straight."),
      h("Write, alone (8 min)"),
      ol(
        "Three brat moves that are fun and in-bounds for your dynamic.",
        "Three that you use when you are actually hurt, tired, or avoiding a talk. Those need the difficult-topics script, not a smirk.",
        "What you want when you get caught. Be honest: the fight, the hold, the laugh, the sex, the proof they will not leave.",
      ),
      h("Share (7 min)"),
      p("Read the lists. The tamer does not argue with your want. They say whether they can offer that catch. If they cannot offer it, that is a negotiation, not a failure to “handle you.”"),
      h("Play one clean brat (5 min)"),
      p("You push on purpose, they catch as agreed, you let yourself be received. Stay for the warmth after. Leaving the moment you are caught is another push — sometimes hot, sometimes just fleeing. Name which one you are doing."),
      h("Remember"),
      p("A good brat makes the frame visible. A frightened person pretending to brat makes the frame cruel. You get to be both people on different days. Pick the tool that matches the day."),
    ),
  },
  {
    key: "edu-brat-needs",
    title: "Recognising a brat's needs",
    category: "education",
    subcategory: "how-to",
    sort: 55,
    body: doc(
      p("A brat is rarely asking for “more rules” in the words they use. They are asking for a need to be met inside a game. If you only hear the sass, you will miss the request. If you only hear the request, you will miss the fun."),
      h("Needs that often wear a brat face"),
      ul(
        "<strong>To be caught.</strong> Proof the frame is real. The need is containment, not chaos.",
        "<strong>To be seen as clever.</strong> A loophole is a gift of attention. If you never acknowledge the craft, they will escalate the volume.",
        "<strong>To be wanted while difficult.</strong> “Will you still hold me if I push?” is an attachment question in costume.",
        "<strong>To discharge energy.</strong> Some bratting is play-hunting. They need a chase, a catch, and a landing, not a lecture.",
        "<strong>To test safety.</strong> After a yellow, a fight, or a drop, a small push can mean “are we still here?” Answer the need, then the game.",
        "<strong>To avoid a straight ask.</strong> Wanting sex, aftercare, or reassurance can come out as sass because asking felt more exposing than being a pest.",
        "<strong>To have an effect.</strong> If nothing they do moves you, they will find something that does. Give them a worthy effect that is still in-bounds.",
        "<strong>To rest from being good.</strong> A well-behaved submissive can starve for permission to be inconvenient. Scheduled brat windows feed that without wrecking Tuesday.",
      ),
      h("How to tell a need from a fight"),
      ol(
        "Look at the body, not only the mouth. Bright eyes and a grin is often play. Flat eyes, a slammed door, or tears they will not name is often a need wearing armour — or a real conflict.",
        "Offer a clean ask once: “Is this play, or do you need something straight?” A brat in play will dodge and grin. A person in need will often sag with relief if you mean it.",
        "If the same push happens after they have been caught well, it may still be play. If it happens after they have been ignored, it is information about attention.",
        "Hunger, hormones, shame, and workdays change the mix. A well-fed, well-held brat is easier to read.",
      ),
      h("Meeting the need without collapsing the game"),
      ul(
        "Catch them in the way you both wrote down, then meet the need in the landing: a hand, a specific praise, a yes to the thing they could not ask for.",
        "If the need is rest, commute the rest of the scene. Mercy is still dominance.",
        "If the need is sex, you can still make them ask. Do not make them invent a crime to get touched.",
        "If the need is proof, a short, boring, reliable ritual will feed them more than a theatrical punishment.",
        "If you cannot tell, pause the dynamic and use ordinary language. You can always restart the game after the truth is on the table.",
      ),
      p("Use the activity <em>Name the brat's need</em> when you want to practise this as a drill, not as a 2am guess."),
    ),
  },
  {
    key: "edu-why-brat",
    title: "Why they brat, and how to deal with it",
    category: "education",
    subcategory: "how-to",
    sort: 56,
    body: doc(
      p("Bratting is a behaviour, not a diagnosis. The same smirk can mean five different things. Your job is not to “win.” It is to read the why, stay in your role if it is play, and drop the role if it is a wound."),
      h("Common whys"),
      ul(
        "<strong>Play.</strong> They want the chase. Deal with it as a game: named moves, named catches, named landings.",
        "<strong>Under-stimulation.</strong> The dynamic has gone slack. Deal with it by feeding protocol or a short scene, not by snapping.",
        "<strong>Over-stimulation.</strong> Too many rules, too much intensity, no rest. Deal with it by subtracting, not by adding a punishment.",
        "<strong>Shame.</strong> They cannot stand being seen as good, or as needy. Deal with it with precise praise and no audience.",
        "<strong>Fear of closeness.</strong> A push just when it got tender. Deal with it by staying, not by chasing them into a bigger fight.",
        "<strong>Unsaid no.</strong> They do not want tonight's plan and cannot say it. Deal with it by making “no” easy, then asking again tomorrow.",
        "<strong>Copied from old rooms.</strong> Bratting that used to keep them safe with someone unsafe. Deal with it slowly, maybe with help, never with humiliation of that history.",
        "<strong>You were sloppy.</strong> They found a hole in the frame. Deal with it by thanking the auditor, then patching the rule.",
      ),
      h("A simple read in the moment"),
      ol(
        "Pause internally for three breaths so you do not take bait with real anger.",
        "Name what you see: “That was a loophole” or “That landed like a real no.”",
        "If it is play, run the catch you both know. Do not invent a new cruelty.",
        "If it is a need, ask one straight question. Then meet it or negotiate a time to meet it.",
        "If it is a fight, say “out of dynamic.” Have the fight as partners. Do not paddle a grievance.",
        "Repair. A brat who is only ever caught and never received will stop bringing you the fun, or they will stop being honest.",
      ),
      h("What not to do"),
      ul(
        "Do not ignore them to “teach a lesson” unless a short, negotiated ignore was the catch — with a clock.",
        "Do not match their volume. You are the wall, not the second brat.",
        "Do not use the relationship, money, food, or sleep as leverage.",
        "Do not tell them they are “not a real submissive.” That sentence does damage you cannot scene your way out of.",
        "Do not skip the debrief. Play that is never talked about turns into a secret language you will misread.",
      ),
      p("Read <em>How to train a bratty submissive</em> and <em>Recognising a brat's needs</em> alongside this. Practise with <em>Decode the brat</em> under Activities."),
    ),
  },
  {
    key: "edu-partner-body",
    title: "Learning your partner's body",
    category: "education",
    subcategory: "how-to",
    sort: 120,
    body: doc(
      p("Porn is a map of somebody else. Your partner is a specific animal: where heat lives, where a tickle becomes a flinch, which knee complains, which words open them, which touch makes them leave the room without leaving the bed. Learning that is a practice, not a talent you either have or do not."),
      h("What you are mapping"),
      ul(
        "<strong>Skin.</strong> Places that want pressure, places that want air, places that are simply “no.”",
        "<strong>Pace.</strong> How long until a touch that was nice becomes too much. How long after a peak they can stand to be touched at all.",
        "<strong>Sound and silence.</strong> Which noises are pleasure, which are performance, which are “get off that.”",
        "<strong>The week in the body.</strong> Hormones, medication, sleep, old injuries. Tuesday's yes is not Saturday's.",
        "<strong>The sexual map.</strong> Clit, cock, perineum, prostate, nipples, neck, inner thigh — and the boring places that are secretly the point.",
        "<strong>The limit map.</strong> Not only genitals. Stomach, feet, face, scars, the place they were hurt before you.",
      ),
      h("How to learn without turning them into a project"),
      ol(
        "Ask out of bed first: “Where do you like to be started?” Write it down. Do not rely on afterglow memory.",
        "Give one new kind of touch at a time. If you change five variables, you will not know what worked.",
        "Use a colour on a body part: green / yellow / never. A full-body scan once a season beats guessing nightly.",
        "Watch the breath more than the porn face. A held breath is data.",
        "Let them show you on their own body, or on yours. Mirroring teaches faster than a lecture.",
        "After, one question only: “Where should I linger longer next time?”",
      ),
      h("Notes worth keeping"),
      p("Keep a private page in Notes or the Journal: lube that does not sting, a angle that finds them, a word that shuts them down, a time of month that wants gentler. Update it as they grow. A body is not a contract you signed once."),
      p("The activity <em>Map your partner's body</em> is a 40-minute version of this you can run without turning it into homework every night."),
    ),
  },
  {
    key: "edu-edging",
    title: "How to edge your partner effectively",
    category: "education",
    subcategory: "how-to",
    sort: 130,
    body: doc(
      p("Edging is riding the climb and choosing not to step off. Done well, it makes the nervous system louder and the asking sweeter. Done badly, it inflames tissue, teaches them to fake, or turns a game into spite."),
      h("The mechanics"),
      ol(
        "Warm the body before you chase the peak. Blood flow is not optional.",
        "Use enough lube. Dry friction makes people come from irritation, not pleasure — or refuse to come at all.",
        "Find their “close” tells: breath, hips, a specific noise, a foot, a look. Ask them to name one tell you may trust.",
        "Approach, then back off before the point of no return. The art is leaving them on the ledge, not shoving them off and pretending it was control.",
        "Change the variable you back off: speed, pressure, location, dirty talk. Do not only stop dead unless they like the crash.",
        "Rest long enough that the next climb is a climb, not a grind on a numb part.",
        "Water. Jaws, hips, and wrists also need breaks.",
      ),
      h("For different bodies"),
      ul(
        "<strong>Clit and vulva.</strong> Indirect can last longer than a bullseye. Some people need a pause on the glans and a move to the shaft of the clit or the surrounding skin. Ask. Do not assume more pressure is more kind.",
        "<strong>Cock.</strong> A tight grip too soon finishes the night. Looser, wetter, slower as they get close. A ring only with a time cap and colour checks.",
        "<strong>Prostate / g-spot.</strong> Edging here can sneak up. Go slower than your pride. Sharp pain is a stop.",
        "<strong>Nipples, thighs, voice.</strong> Some people edge from dirty talk or from being watched. That still counts. Do not add genital touch just to make it “real.”",
      ),
      h("Control versus cruelty"),
      p("If they asked for mean denial, you can still be precise. If they asked to be taken care of, edging is a gift of attention, not a test they can fail. A body that comes “too soon” is a body, not a brat — unless they are obviously performing a loophole you both think is funny."),
      ul(
        "Agree whether a slip is a giggle, a reset, or a punishment. Write it down so lust does not prosecute.",
        "Ruined orgasms are a specific kink. Do not “accidentally” ruin one.",
        "Stop if they look like they are enduring. Endurance is not the same as heat.",
        "Aftercare for a night they did not come: they may feel raw or clingy. Plan for that, not only for the ones who float.",
      ),
      p("Practise with <em>Edging lab</em> under Activities. Keep what you learn in the body-map note."),
    ),
  },
  {
    key: "edu-orgasm-command",
    title: "Orgasm on command",
    category: "education",
    subcategory: "how-to",
    sort: 140,
    body: doc(
      p("Coming when they are told — with a hand, a toy, or eventually with a word — is trained pairing, not magic. Some bodies will never be fully reliable. That is not a moral failure. It is anatomy, history, medication, and luck. Train the skill. Do not train self-hate."),
      h("With stimulation"),
      ol(
        "Pick a cue: a word, a snap, a tap. Use the same one for weeks.",
        "Bring them to the edge with the touch they already come from. Do not invent a new technique in week one.",
        "When they are truly close, give the cue and keep doing exactly what was working. The cue rides the orgasm, it does not replace the work yet.",
        "If they come, mark it: praise, the word “good,” a still hand. You are teaching the nervous system that the cue predicted the peak.",
        "If they do not, do not punish. Back off, rest, try once more or stop for the night. Shame makes orgasms hide.",
        "Repeat across many sessions, not one heroic evening. Pairing is boring until it is not.",
        "Over time, shorten the runway: less build, same cue. Only then reduce the stimulation.",
      ),
      h("Without stimulation"),
      p("This is later, and it is not guaranteed. You are asking a body to finish on memory, voice, and tension."),
      ol(
        "Only start this after the cue already works with touch most of the time.",
        "Use the same cue. Add a posture or a breath pattern they already associate with being close.",
        "Let them clench, rock, or breathe — that is still their body helping. “Without stimulation” means without your hand or a toy, not without their own muscle.",
        "Some people need a fantasy spoken, or a memory of the last time. That is allowed.",
        "Success may look like a small orgasm, a ruined one, or a wave that is more like a shiver. Celebrate the pairing, not a porn money-shot.",
        "If nothing happens, they have still practised arousal on a word. End with closeness, not a scoreboard.",
        "Never require this in public, at work, or as a proof of ownership. A body that can do this is offering something rare. Treat it that way.",
      ),
      h("What gets in the way"),
      ul(
        "SSRIs, alcohol, pain, being watched with contempt, needing to pee, being cold, being rushed, being told they “should have by now.”",
        "Switching the cue every session. Pick one.",
        "Punishing a miss. You will train freeze.",
        "Trying to stack humiliation, pain, and command-orgasm on night one.",
      ),
      p("Run <em>Orgasm on command — with stimulation</em> for a few weeks before you open the without-stimulation activity. Keep notes. Bodies change."),
    ),
  },
  {
    key: "act-body-map",
    title: "Map your partner's body",
    category: "exercises",
    subcategory: "body",
    sort: 130,
    body: doc(
      p("Time: 40 minutes. Phones away. One giver, one receiver, then swap if you want. This is research, not a performance."),
      h("Setup"),
      p("A yes/yellow/no list for tonight. Lube. A towel. Ordinary light — you need to see. Agree that “no” on a body part is not a rejection of the person."),
      h("The scan"),
      ol(
        "Receiver lies down. Giver starts at the scalp and moves slowly: scalp, nape, ears, mouth (if allowed), throat, shoulders, inner arms, hands, chest, belly, hips, inner thighs, knees, calves, feet, then the sexual map you both named.",
        "On each place, try two pressures and two speeds. Wait. Watch breath.",
        "Receiver says green, yellow, or never — or a number 1–5 if they like numbers. Giver writes it down. Do not argue with a never.",
        "Mark three “linger here” spots and one “do not surprise me here.”",
      ),
      h("The sexual close (optional)"),
      p("If you are both still in it, give five minutes of the best thing you learned. No proving. Then water."),
      h("Debrief"),
      p("Read the notes back. Put keepers in Notes. Do this again in a season, or after a medication change, a birth, a surgery, or a long drought. Bodies move."),
    ),
  },
  {
    key: "act-edging-lab",
    title: "Edging lab",
    category: "exercises",
    subcategory: "body",
    sort: 140,
    body: doc(
      p("Time: 25–40 minutes. One person is edged. The other is the operator. Swap another night. Read <em>How to edge your partner effectively</em> first."),
      h("Agree"),
      ul(
        "Whether a slip is a laugh, a reset, or the end.",
        "Whether they will come at the end or not. Do not change that in the last ten seconds unless they ask.",
        "A colour check every edge.",
      ),
      h("The lab"),
      ol(
        "Warm-up until the body is actually interested, not polite.",
        "Edge one: stop when they say “close.” Note what you were doing.",
        "Rest until they can talk in a full sentence.",
        "Edge two: stop one breath earlier. Note the tell you used.",
        "Edge three: change only one variable (speed, or location, or talk).",
        "If tonight includes a finish, use the same technique that worked, plus the cue if you are also training command.",
        "If tonight is denial, stop after three, wrap them, and do not add a barbed joke.",
      ),
      h("Write"),
      p("One tell. One technique that lasted. One that rushed them. Put it in the body-map note. That is the whole point of a lab."),
    ),
  },
  {
    key: "act-orgasm-touch",
    title: "Orgasm on command — with stimulation",
    category: "exercises",
    subcategory: "body",
    sort: 150,
    body: doc(
      p("Time: 20–30 minutes, twice a week if you can, not once as a stunt. Pick a single cue and do not change it this month."),
      h("The drill"),
      ol(
        "Arousal first. No cue until they are actually close.",
        "When they are close, give the cue and keep the exact stimulation that was working.",
        "If they come, still the hands, praise, repeat the cue once more in a warm voice so the pairing sticks.",
        "If they do not, rest. One more try or stop. No scoreboard.",
        "After three sessions of mostly-yes, you may shorten the build by a little. Not by half.",
      ),
      h("Rules"),
      ul(
        "Same time of day if you can. Bodies like context.",
        "No new kinks in this drill. The drill is the pairing.",
        "If they are on a medication that dulls orgasm, lower the ambition. Celebrate a swell, a shiver, a “close.”",
        "Write dates and yes/no in the Journal. Patterns beat memory.",
      ),
    ),
  },
  {
    key: "act-orgasm-voice",
    title: "Orgasm on command — without stimulation",
    category: "exercises",
    subcategory: "body",
    sort: 160,
    body: doc(
      p("Time: 15 minutes. Only after the with-stimulation drill works most of the time. This may never be reliable. Treat any success as a gift, not a standard."),
      h("The drill"),
      ol(
        "They take the posture you used in the touch drill. You use the same cue.",
        "They may breathe, clench, rock, or hear you describe the last time they came. You do not touch genitals. A hand on a sternum or nape is allowed if that is an anchor, not a cheat you pretend not to notice — agree it.",
        "Give the cue when they say they are close, or after a build of talk and breath you have used before.",
        "Wait. Do not stare like a referee. Stay kind in the face.",
        "Whatever happens, praise the attempt. Then ordinary closeness.",
      ),
      h("If nothing happens"),
      p("That is the most common outcome. Do not add a toy “just to finish the job” unless they ask. You can run the with-stimulation drill another night. You may not punish a quiet body."),
      h("If something happens"),
      p("Mark it. Same cue next time. Do not immediately raise the difficulty or take it public."),
    ),
  },
  {
    key: "act-brat-needs",
    title: "Name the brat's need",
    category: "exercises",
    subcategory: "bratting",
    sort: 130,
    body: doc(
      p("Time: 20 minutes, out of scene. You are practising the read from <em>Recognising a brat's needs</em>."),
      h("Alone, five minutes"),
      p("Brat (or the person who brats) writes three recent pushes and, for each, the need they suspect was underneath: caught, seen, wanted, discharge, safety-check, avoided ask, effect, rest. They may write “it was just fun.” That is a valid need too — play."),
      h("Together"),
      ol(
        "Read the list. The tamer does not argue. They may say which need they thought it was.",
        "Pick one need for this week. Agree a clean way to ask for it, and a play way to ask for it.",
        "Agree the catch if they still choose the play way.",
      ),
      h("This week"),
      p("When a push happens, the tamer may ask once: “Play or need?” Then they either catch or meet. Debrief on Sunday in one line each."),
    ),
  },
  {
    key: "act-why-brat",
    title: "Decode the brat",
    category: "exercises",
    subcategory: "bratting",
    sort: 140,
    body: doc(
      p("Time: 15 minutes after a real brat moment, not in the heat of it. Wait until you can sit. Read <em>Why they brat, and how to deal with it</em> first."),
      h("The five questions"),
      ol(
        "What did they actually do, in one sentence, without adjectives.",
        "What did it get them (attention, delay, sex, a rise, space, a laugh).",
        "Was the body play-bright or fight-flat.",
        "What would a clean ask have been.",
        "What catch or care should we run if a twin of this shows up tomorrow.",
      ),
      h("Output"),
      p("One line in Notes: “When X, we will Y.” If Y is a talk, put it on the calendar. If Y is a catch, put it in Punishments or Training so you do not invent it angry."),
    ),
  },
];
