import type { Experience } from "@/lib/experience";
import type { WeekKind, WeekPrompt, WeekPromptBody } from "@/lib/weekly-talk";

function body(
  title: string,
  description: string,
  easy: string,
  hard: string,
  extreme: string,
): WeekPromptBody {
  return { title, description, easy, hard, extreme };
}

function slugId(kind: WeekKind, title: string) {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
  return `${kind}:${slug}`;
}

function entry(
  kind: WeekKind,
  kinks: string[],
  min: Experience | undefined,
  dominant: WeekPromptBody,
  submissive: WeekPromptBody,
): WeekPrompt {
  return { id: slugId(kind, dominant.title), kind, kinks, min, dominant, submissive };
}

export const WEEKLY_PROMPTS: WeekPrompt[] = [
  entry(
    "communication",
    ["protocol", "verbal", "training", "power-exchange"],
    "curious",
    body(
      "Say one instruction. They do it once",
      "Pick one short instruction they can actually do in this room. Say it once, in a calm voice. Do not repeat it. Do not add a second one. They do it. You say thank you, or you say that was good, and you use their name. If they did not hear you, that is on you — say it again once, then stop. After: water. Write the instruction in Journal if you want to use it again.",
      "One instruction. Sit down. They sit. Thank you. Name. Drink water.",
      "One instruction that uses their body: kneel on a cushion, or put your hands on your thighs. They do it. You thank them. They stand when you say so.",
      "One instruction, then 2 minutes of holding it. You do not fill the quiet with extra words. Then their name, and they may move.",
    ),
    body(
      "Hear one instruction. Do it once",
      "They say one short instruction. You do it. You do not have to guess a second one. After: water, your name.",
      "Sit when they say sit. Hear thank you. Drink water.",
      "Kneel or hands on thighs if that is what they asked. Stand when they say so.",
      "Hold it for 2 minutes. You may ask, in ordinary words, if you did not hear.",
    ),
  ),
  entry(
    "communication",
    ["praise", "verbal", "service"],
    "curious",
    body(
      "Three true praises before they sleep",
      "Before bed, say 3 true sentences about how they were today. Be specific. Do not use empty lines like you are amazing. Do not turn praise into a new task. If the words start to sound like shame, make them smaller, or stop. After: they only have to hear them. The words can live in a message they can read tomorrow.",
      "3 lines, one night. They may say thank you or stop. Stop means stop.",
      "3 nights this week. Same rule. No extra tasks attached.",
      "Every night this week. Sunday ask which line actually landed. Keep those. Stop the ones that felt like acting.",
    ),
    body(
      "Three true praises you have to take before sleep",
      "You hear 3 true lines. You may say stop. The message can stay for morning.",
      "One night. Thank you, or stop.",
      "Three nights. You may ask for paper if a low mood steals spoken words.",
      "Every night. Say on Sunday which line helped.",
    ),
  ),
  entry(
    "communication",
    ["verbal", "humiliation", "degradation"],
    "seasoned",
    body(
      "Dirty talk from a page you wrote",
      "While clothed, write 5 words or short lines they want to hear. Only those words. Do not make up new mean words in the heat. Read the list once. Stop. Then say the opposite kind sentences, as true. If either of you laughs from discomfort, it is over. Do not do this in public. Write a kind morning note now.",
      "Read the 5 lines. Stop. Write the 5 kind opposites in the same notebook.",
      "One line, repeated. Then its opposite. Morning note already drafted.",
      "The full list, still once, still with the repair the same night. Do not add spanking or bondage the same night.",
    ),
    body(
      "Dirty talk from a page you helped write",
      "Only the page you helped write. You can stop it. After: the opposite sentences. A morning note.",
      "The 5 lines once. Then the kind opposites.",
      "One line, then its opposite. You may stop after the first.",
      "The full list, still once. You may keep it on paper and not run it.",
    ),
  ),
  entry(
    "communication",
    ["verbal", "degradation", "orgasm-control", "denial"],
    "practiced",
    body(
      "Tease them with words while you edge them",
      "Use your hand or a toy they already know. Bring them close to orgasm, then stop. While you do that, use playful mean words from a list you wrote while clothed — teasing, not new insults. Examples they asked for: greedy, patient, not yet. Ask for a number from 1 to 10. 8 means you take your hand away. After: water, a towel, their name, and a clear yes or no about coming later. If the words land as real shame, stop the words. Keep the care.",
      "2 minutes on, 1 minute off, 3 times. One teasing line from the list each stop. Then offer: come now, wait, or be held.",
      "Same 3 rounds. They keep their hands still. You may repeat one line. They may still ask you to stop the words.",
      "A longer hold at about 7. Keep the list. Then the planned yes or no. Do not add new mean words because they looked close.",
    ),
    body(
      "Hear the tease while they edge you",
      "They touch you. They stop. They use words from a list you helped write. You say numbers. 8 means stop. After: water, towel, a clear yes or no about later.",
      "3 rounds. One teasing line each stop. Then say honestly: come now, wait, or be held.",
      "Hands still. You may still ask them to stop the words.",
      "A longer wait. You may ask for the kind sentences instead of the tease.",
    ),
  ),
  entry(
    "communication",
    ["protocol", "ownership", "verbal"],
    "curious",
    body(
      "A name they asked for, used for 10 minutes",
      "Pick a name they already said yes to: Sir, Ma'am, a pet name, or their real name said with care. Use it for 10 minutes at home. When the timer rings, go back to ordinary names unless they ask to keep it. Do not use a name they did not pick. After: their legal name, water.",
      "5 minutes at the table. The name, then their legal name. Drink.",
      "10 minutes. The name while they sit or kneel. Then legal name and tea.",
      "An evening at home. The name inside. Legal name if anyone else can hear, including through a wall.",
    ),
    body(
      "A name you asked for, used for 10 minutes",
      "They use a name you already said yes to. You get your legal name back. After: water.",
      "5 minutes. Then your legal name.",
      "10 minutes. Then tea and your name.",
      "An evening at home. You may ask for your legal name at any time.",
    ),
  ),
  entry(
    "communication",
    ["verbal", "protocol", "power-exchange"],
    "curious",
    body(
      "You tell them what you will do. Then you do it",
      "Before you touch them, say the next step in plain words. Then do only that. Then tell the next step. They can say no to a step. No means you skip it, not that the night is over unless they want it over. After: say you are done. Their name. Water.",
      "3 steps. Clothes stay on. Name each one. Then done.",
      "5 steps. They may say skip. You skip. Then their name.",
      "A longer map you named while clothed. Still one step at a time. Still no extra surprise.",
    ),
    body(
      "They tell you what they will do. Then they do it",
      "You hear the next step. You may say no. After: you are done, your name, water.",
      "3 steps. Clothes on. You may skip any step.",
      "5 steps. Skip still works.",
      "A longer map. You may stop the whole map with ordinary words.",
    ),
  ),
  entry(
    "public",
    ["exhibitionism", "orgasm-control", "sensation-play"],
    "practiced",
    body(
      "A remote toy on low, a short shop",
      "They wear a small vibrator under ordinary clothes. You hold the remote. Use a toy they have already worn. Agree a stop word by text. Keep it on the lowest setting. A shop or a walk, 40 minutes or less. If they cannot walk easily, you find a bathroom or you go home. Do not show off to people on the street. Strangers are not in the scene. After: toy out, wash, water, sit.",
      "A 10-minute walk around the block on low. Then home. Out. Water.",
      "A short known shop, 20 minutes. One text that says the stop word means off now. You do not raise it in the aisle.",
      "40 minutes max. Still low. If their face looks like panic, not heat, it is over and you go home. Praise the abort.",
    ),
    body(
      "A remote toy they hold, a short shop you take",
      "You wear it. They hold the remote. Stop word by text. Low only. Strangers are not in the scene. After: out, wash, water.",
      "10-minute walk. Then home.",
      "A short known shop. Text stop if you need it off.",
      "40 minutes max. You do not have to finish the shop.",
    ),
  ),
  entry(
    "public",
    ["protocol", "power-exchange", "voyeurism"],
    "curious",
    body(
      "A look across the table that means I have you",
      "Agree one look. It means I have you. Use it once in a cafe, a park, or at dinner out. Nobody else should be able to read it. Do not add a second signal this week. After: a short text on the way home that says the look landed, or that it felt silly. Silly is allowed.",
      "Practise the look at home for 1 minute. Then use it once at a table you already sit at.",
      "Use it once on a real outing. Then tea as people.",
      "Use it twice this week, same look. If they miss it, you do not punish the miss. You try again or you drop it.",
    ),
    body(
      "A look across the table that means they have you",
      "One look you both know. Nobody else should read it. After: a text that says it landed, or that it felt silly.",
      "Practise at home. Then once at a table you already sit at.",
      "Once on a real outing. Then tea.",
      "Twice this week. Missing it is not a fail.",
    ),
  ),
  entry(
    "public",
    ["exhibitionism", "ownership", "protocol"],
    "curious",
    body(
      "A secret item under clothes on a short walk",
      "You choose one item they already own: underwear, a bracelet, a plug they have already worn. They wear it under normal clothes on a short walk you already take. They can take it out in a bathroom. After: home, item off, their name. Do not ask them to flash anyone. Do not take photos in public.",
      "A bracelet or a pair of underwear. 15-minute walk. Off at home.",
      "Underwear you chose. A half-hour known walk. Off at home. One check-in text.",
      "A plug they have already worn, a short walk, bathroom access the whole time. Out the moment they say so, including in ordinary words.",
    ),
    body(
      "A secret item they chose, on a short walk you take",
      "One item you already own, under normal clothes. You can take it out. After: home, off, your name. No photos in public.",
      "A bracelet or underwear. 15-minute walk. Off at home.",
      "Underwear they chose. A known walk. One text. Off at home.",
      "A plug you have already worn, only if you still want it. You can take it out in a bathroom. That is care.",
    ),
  ),
  entry(
    "public",
    ["exhibitionism", "orgasm-control", "denial"],
    "practiced",
    body(
      "One bathroom stall. One touch. Then back to you",
      "In a place with a lockable stall (cafe, shop, cinema). They go in. They touch their genitals once, through clothes or under, for no more than 60 seconds. They do not come. They come back to the table. You do not follow them in. You do not involve other people. After: home, water, a clear yes or no about coming later. If the stall feels unsafe, skip it and do the 60 seconds at home. Skipping is the skill.",
      "Practise the 60 seconds at home first. Then, if it still feels good, once in a stall you know. Back to the table. No coming.",
      "Once on a real outing. 60 seconds. Back. A kind look. Home.",
      "Twice this week, still 60 seconds, still no coming in the stall. A planned yes later so the week is not only waiting.",
    ),
    body(
      "One bathroom stall. One touch. Then back to them",
      "Lock. 60 seconds. You do not come. You go back. If it feels unsafe, you skip it and do it at home. That is care.",
      "Practise at home. Then once in a stall you know, if you still want it.",
      "Once on a real outing. Back to the table.",
      "Twice this week. You still get a planned yes later.",
    ),
  ),
  entry(
    "public",
    ["verbal", "orgasm-control", "exhibitionism"],
    "curious",
    body(
      "A text that heats them up while they are out",
      "They are at work, on a bus, or in a shop. You send 1 to 3 short texts that are dirty enough to heat them up, clean enough that a stranger glancing at a phone would not know. No photos of genitals. They may reply later. After: a kind closing text so they are not left hanging. Do not stack 20 messages.",
      "One text. One kind close an hour later.",
      "Three texts across an afternoon. A close before they sleep.",
      "A whole outing. Still 3 texts max. A planned yes or a planned wait when they get home. Do not make them reply at work.",
    ),
    body(
      "A text that heats you up while you are out",
      "Short. Safe to glance at. You do not have to reply at work. You get a kind close so you are not left hanging.",
      "One text. One kind close.",
      "Three texts. A close before sleep.",
      "A whole outing. You may ask them to stop. That is a complete answer.",
    ),
  ),
  entry(
    "public",
    ["ownership", "protocol", "marking"],
    "curious",
    body(
      "A hand on the small of their back in a queue",
      "In a real queue — shop, cinema, station — put your hand on the small of their back. Ordinary. Claimed. Nobody else should clock it as a scene. Take the hand away if they shift away. After: a squeeze of the hand when you are back in private. That is the close.",
      "Practise at home, 10 seconds. Then once in a real queue.",
      "Once on an outing you already planned. Then the private squeeze.",
      "Each time you queue together this week. If they shift away, the hand comes off. That is the rule working.",
    ),
    body(
      "A hand on the small of your back in a queue",
      "Ordinary. Claimed. You may shift away. The hand should come off. After: a squeeze in private.",
      "Practise at home. Then once in a real queue.",
      "Once on a planned outing. Then the private squeeze.",
      "Each queue this week. Shifting away is allowed.",
    ),
  ),
  entry(
    "scene",
    ["protocol", "service", "power-exchange"],
    "curious",
    body(
      "You wash them. They stay still",
      "A shower or a bath you both fit, at home. You wash them. They keep their hands on the wall or on their thighs unless they need to be safe. Agree a time: 10 minutes is enough. Water temperature they can stand. After: towel, their name, a robe, water to drink. Do not add sex unless that was the plan. Stopping if they are cold is the skill.",
      "10 minutes. Back and hair. They stay still. Towel. Name.",
      "15 minutes. Whole body they offered. They may speak. Then robe and a drink.",
      "20 minutes. Still. Then you dry them. Sit. 10 minutes of quiet. Do not rush the next thing.",
    ),
    body(
      "They wash you. You stay still",
      "You keep still unless you need to be safe. You may say the water is too hot. After: towel, your name, a drink.",
      "10 minutes. Back and hair. Then towel and your name.",
      "15 minutes. Body you offered. You may speak. Then a robe.",
      "20 minutes. Then quiet sitting. You may ask that this be the whole scene.",
    ),
  ),
  entry(
    "scene",
    ["spanking", "impact-play", "sadomasochism"],
    "practiced",
    body(
      "Over-the-knee spanking is the whole scene",
      "At home. The spanking is the scene, not a warm-up for sex. Clothes on first. Hand only. Agree the number while clothed. Count out loud. Check between sets. Landing is longer than the spanking: sit them up, water, a blanket, a hand on their back, their name. Do not add a paddle unless that was the plan.",
      "Clothes on. 10, check, 10. Sit up. Water. Blanket. 10 quiet minutes.",
      "Underwear if they asked. Same written number. Last touches are a hand. Then 15 minutes of landing.",
      "Bare if they asked. Two sets, still the written number. Marks that show at work need a separate yes. Landing is 20 minutes.",
    ),
    body(
      "Over-the-knee spanking is the whole scene — you take it",
      "You get a landing longer than the spanking. After: sit up, water, blanket, your name.",
      "Clothes on. 10, check, 10. Then 10 quiet minutes.",
      "Underwear if you asked. Then 15 minutes of landing.",
      "Bare if you asked. Say if you sit at work tomorrow. You still get the long landing.",
    ),
  ),
  entry(
    "scene",
    ["denial", "power-exchange", "orgasm-control"],
    "curious",
    body(
      "Kissing they cannot start",
      "At home. You kiss them. They do not start the kiss. They may kiss back when you say so. Set a timer: 10 minutes. If they start, you pause, smile, and begin again, or you stop. Stopping is allowed. After: they may kiss you freely, or you hold them without kissing. Say which. Water.",
      "5 minutes. Forehead and mouth. They wait. Then they may kiss you back. Drink water.",
      "10 minutes. You start every kiss. Then 5 minutes where they may start. Then names.",
      "15 minutes. No sex after unless that was the plan. Being not allowed to start can be the whole heat.",
    ),
    body(
      "Kissing you cannot start",
      "They start. You wait. You may kiss back when they say so. After: free kissing or a hold. Water.",
      "5 minutes. Then you may kiss them back.",
      "10 minutes of waiting. Then 5 minutes you may start.",
      "15 minutes. You may ask that this stay the whole scene.",
    ),
  ),
  entry(
    "scene",
    ["protocol", "ownership", "exhibitionism"],
    "curious",
    body(
      "A bench: they sit close. You decide when they may touch",
      "In a park or on a quiet street, sit on a public bench. They sit close. Ordinary clothes. You decide when they may put a hand on your leg. Nobody else is in the scene. No toys. No kissing that would make a stranger uncomfortable. 10 minutes. After: walk home or to the car as people, then a private squeeze.",
      "5 minutes. Close. No extra touch. Then a private squeeze.",
      "10 minutes. One allowed hand on a leg when you say so. Then you walk.",
      "20 minutes. Still ordinary. If the bench gets busy, you leave. Leaving is the scene going well.",
    ),
    body(
      "A bench: you sit close. They decide when you may touch",
      "Public bench. Ordinary. You wait. You may put a hand on a leg when they say so. After: a private squeeze.",
      "5 minutes. Close. Then a private squeeze.",
      "10 minutes. One allowed hand when they say so.",
      "20 minutes. If it gets busy, you leave. That is care.",
    ),
  ),
  entry(
    "scene",
    ["cnc", "breath-play"],
    "established",
    body(
      "Want, fear, out — write it, do not run it",
      "You do not run CNC (pretend force) or breath play (hands or toys on the throat or airway) tonight. You write it. Wanting is not consent for tonight. One notebook. Three columns: want, fear, out. Include who would know where you are, what sober and fed looks like, the tap, the aftercare, what never happens. Sleep on it. If it is still a yes in the morning, it goes on a calendar, not into the next hour. Closing the notebook is aftercare.",
      "Want / fear / out. Tea. Notebook closed. No scene. That is the whole prompt.",
      "A fuller page: aftercare, a trusted third who would know you are planning (not doing), what never happens. Still no scene. Still sleep.",
      "Read it in the morning. Calendar only after sleep — or the page scares you, and that is a complete answer. Do not write this on a train.",
    ),
    body(
      "Want, fear, out — you write, you do not have to be brave tonight",
      "You write. You do not run it tonight. Closing the notebook is aftercare.",
      "Want / fear / out. Tea. Closed. No scene.",
      "A fuller page. Still no scene. Still sleep.",
      "Morning read. You may refuse the calendar. That is a complete answer.",
    ),
  ),
  entry(
    "roleplay",
    ["roleplay", "protocol", "verbal"],
    "curious",
    body(
      "Late to work — you are the boss",
      "At home. You pretend they are late. You are the boss. A kitchen timer is the meeting. 3 to 8 minutes. Pick a tone first: kind, firm, or exacting — not all three. They may speak. When the timer rings, you are yourselves. Names. Water. Silly is allowed. Do not trap this at a real workplace.",
      "3 minutes at the table. One late line. One boss line. Timer. Names. Laugh if you need to.",
      "5 minutes. They stand. You sit. Then names and tea.",
      "8 minutes, a little more heat, still a timer, still names back. No touching until a word you picked in advance.",
    ),
    body(
      "Late to work — they are the boss",
      "You are late. They are the boss. A timer. Then your name back. Silly is allowed.",
      "3 minutes. Then names.",
      "5 minutes. You stand. Then tea.",
      "8 minutes. You may stop the scene with ordinary words.",
    ),
  ),
  entry(
    "roleplay",
    ["roleplay", "service", "objectification"],
    "curious",
    body(
      "You hired them for two hours",
      "At home. They are hired help for two hours. Write 3 jobs on a card: pour water, fold a throw, stand and wait. You thank or you correct once. Bathroom and water in an adult voice. When the timer ends, the card goes away and you say their real name. After: sofa, food, a check on whether it felt like play or like being used up. Repair the second.",
      "20 minutes. 1 job. Thank you. Name. Drink.",
      "1 hour. 3 jobs on a card. Then the card away and their name.",
      "2 hours. Still 3 jobs. If they use the adult voice, you answer the adult. Card in a drawer on time.",
    ),
    body(
      "They hired you for two hours",
      "You do the jobs on the card. You get your name back. Adult voice always works. After: sofa, food.",
      "20 minutes. 1 job. Then your name.",
      "1 hour. 3 jobs. Then the card away.",
      "2 hours. You may use the adult voice. You should get the adult back.",
    ),
  ),
  entry(
    "roleplay",
    ["roleplay", "training", "protocol"],
    "curious",
    body(
      "Homework check",
      "At home. They bring you one thing they did: a task ticked, a journal line, a photo of a made bed. You sit. They stand or kneel. You look. You say one true good thing. You may ask one question. Then tea. Pass or fail only with affection. End on what passed.",
      "Stand, one item, one kind sentence, tea. That is the whole scene.",
      "Kneel if they want. Two items. One question. Then tea as people.",
      "A fuller check of the week. Still end on what passed. Still tea. Do not invent a new standard in the middle.",
    ),
    body(
      "Homework check — you bring the work",
      "You bring one thing. You hear what passed. You get tea.",
      "One item. One kind sentence. Tea.",
      "Two items. One question. Then tea as yourself.",
      "The week. You still get what passed, not a list of sins, unless you asked.",
    ),
  ),
  entry(
    "roleplay",
    ["pet-play", "roleplay", "ownership"],
    "curious",
    body(
      "A pet coming home from a walk",
      "At home. They come in. They sit on a cushion. You take off a collar or a necklace. You give water. You say a pet name if they asked for one. 10 minutes. Then their real name and the sofa. No outdoor leads. No cages. If they laugh from discomfort, the pet is over and the person is held.",
      "5 minutes. Cushion. Water. Real name. Snack.",
      "10 minutes. Jewellery on, then off with their name. Three allowed asks.",
      "20 minutes in the house only. Pet names inside. Legal name if anyone else can hear.",
    ),
    body(
      "You come home as a pet",
      "Cushion. Water. A name that comes back. After: sofa, your name.",
      "5 minutes. Then your name and a snack.",
      "10 minutes. Jewellery off with your name. Three asks.",
      "20 minutes. You may use the adult voice.",
    ),
  ),
  entry(
    "roleplay",
    ["roleplay", "power-exchange", "protocol"],
    "curious",
    body(
      "Inspection at the door",
      "At home, or at the door after a short outing. They stand. You look: clothes, posture, eyes. You say one true thing you see. You may adjust a collar, a necklace, or a stray hair. 2 minutes. Then their name and the rest of the evening. Do not inspect genitals at a real door. Do not do this if a neighbour can see.",
      "2 minutes in the hallway, door closed. One true thing. Name. Drink.",
      "After a real short outing. Stand. Look. One true thing. Then tea.",
      "Each homecoming this week if you are both in. Skip if someone else is there. Skipping is care.",
    ),
    body(
      "Inspection at the door — you stand",
      "You stand. They look. You hear one true thing. You get your name back. Not at a door a neighbour can see.",
      "2 minutes, door closed. Then your name.",
      "After a short outing. Then tea.",
      "Each homecoming this week if you are both in. You may skip if someone else is there.",
    ),
  ),
  entry(
    "roleplay",
    ["roleplay", "verbal", "service"],
    "curious",
    body(
      "Waiter and diner at your own table",
      "At home. They serve a simple thing you already have: water, toast, tea. You stay in the diner seat. They stay in the waiter role until a timer rings, 10 minutes. Thank them in role, then use their real name. Silly is allowed. After: you both eat as yourselves.",
      "10 minutes. Water poured. Thank you. Names. Eat.",
      "20 minutes. A small plate. Then names and the rest of the meal as people.",
      "A whole simple meal. Still a timer for the role. Names back before dessert. Do not add humiliation unless that is on a written list.",
    ),
    body(
      "Waiter at your own table — you serve",
      "You serve. They sit. You get your name back. Then you both eat as yourselves.",
      "10 minutes. Water. Then your name.",
      "20 minutes. A small plate. Then names.",
      "A whole simple meal. You may ask for your name back before dessert.",
    ),
  ),
  entry(
    "task",
    ["service", "exhibitionism"],
    "curious",
    body(
      "A photo of the bed made by a time you set",
      "They make the bed. They send a photo of the bed, not of their body, by a time you set. You reply the same day with one true good sentence. Do not ask for a second photo because the first was easy. Do not critique the angle. Delete if they ask later, including at 2 a.m.",
      "One photo by 10am. One true sentence back.",
      "Three mornings this week. Answer each one the same day.",
      "Every morning this week. Sunday you decide if it lives. Praise the boring. That is the kink.",
    ),
    body(
      "A photo of the bed you made, by a time they set",
      "A photo of the bed, not of your body. You get one true sentence back. You may ask for it to be deleted.",
      "One photo by 10am.",
      "Three mornings. You get an answer each day.",
      "Every morning this week. You may ask to stop on Sunday.",
    ),
  ),
  entry(
    "task",
    ["protocol", "training", "service"],
    "curious",
    body(
      "Sixty seconds of kneeling before dinner",
      "Before dinner, they kneel on a cushion for 60 seconds. You set a timer. You may put a hand on their shoulder. You say their name. They stand. You eat. Write it in Tasks. If work or body makes it impossible, they tell you, and you thank the telling. Do not add a second ritual mid-week.",
      "Practise once, not at dinner. 60 seconds. Name. Stand. Log it.",
      "Once a day, three days this week, before a meal you already eat together.",
      "Each dinner you share this week. Sunday: keep, change, or stop. Stopping is a skill.",
    ),
    body(
      "Sixty seconds of kneeling before dinner — you hold it",
      "Cushion. 60 seconds. Your name. Stand. Eat. A miss you report is not a fail.",
      "Practise once. Log it.",
      "Three meals this week.",
      "Each shared dinner. You may ask to stop on Sunday.",
    ),
  ),
  entry(
    "task",
    ["orgasm-control", "denial", "chastity", "protocol"],
    "practiced",
    body(
      "Permission to come, written in Journal",
      "For this week, they write in Journal when they want to come, whether they asked, what you said, and how they felt after. You answer the same day. No maybe overnight. This is not a week of automatic no. Put one planned yes on the calendar so the week is not only waiting. Sunday you read it like weather, not like evidence.",
      "One note: time, ask, answer, after. If no, add one kind thing they may have instead.",
      "Three days of notes. One planned yes. Ordinary language only.",
      "The whole week. Sunday read as people first. If the waiting was lonely, shorten the next week.",
    ),
    body(
      "Permission to come — you write the ask in Journal",
      "Asking is the task. You get an answer the same day. The log is weather, not evidence.",
      "One note. If no, you get one kind thing instead.",
      "Three days. A planned yes on the calendar.",
      "The week. Say on Sunday if the waiting was hot or just lonely.",
    ),
  ),
  entry(
    "task",
    ["ownership", "protocol", "exhibitionism"],
    "curious",
    body(
      "Wear the item you chose, at home, until a time",
      "You choose one item they already own: a collar, a necklace, a bracelet, or a pair of underwear. They wear it at home until a time you name. You take it off with their real name. A collar is not a contract. They may take it off if family walks in. That is care.",
      "20 minutes. Sit. On. Off with their name. Water.",
      "The evening at home. Off before sleep. Check if they go quiet when it goes on — like, freeze, or want. Those are different.",
      "A day at home. On in the morning. Off at a time you named. Two items if you can: a day piece and a play piece, two rules.",
    ),
    body(
      "Wear the item they chose, at home, until a time",
      "One item you already own. Off with your real name. You may take it off if family walks in.",
      "20 minutes. Off with your name.",
      "The evening. Off before sleep. You may ask what it means again.",
      "A day at home. You may take it off at the door. That is care, not a fail.",
    ),
  ),
  entry(
    "task",
    ["protocol", "service", "training"],
    "curious",
    body(
      "One check-in at a named time",
      "Pick a time this week. They send a short message at that time: here, green or yellow, and one true line about the day. You reply the same day. Do not turn a late check-in into a punishment on the spot. Write it in Tasks. After the week: keep, move the time, or stop.",
      "One check-in. One true reply.",
      "Three days, same time. Reply each day.",
      "Each day this week. Sunday decide if the time was kind. A miss they report is not a fail.",
    ),
    body(
      "One check-in at a named time you keep",
      "A short message: here, green or yellow, one true line. You get a reply. A miss you report is not a fail.",
      "One check-in. You get a reply.",
      "Three days. Same time.",
      "Each day this week. You may ask to move the time.",
    ),
  ),
  entry(
    "task",
    ["impact-play", "spanking", "sadomasochism"],
    "practiced",
    body(
      "Twenty spanks on a calendar slot",
      "Put a 20-minute window on the calendar this week. Hand or a paddle you already know. Clothes on first. Count 20. They may lower the number on the day. They may not raise it because the afternoon was bad. Warm up, count, check, hand to close. Log it in Training, not Punishments, unless punishment is the flavour you named. A cancelled homework with honesty still counts.",
      "Calendar the window. Run 20 with clothes on. Hand to close. Stop if the day turned.",
      "Ask about tomorrow's clothes before you start. Two sets of 10 only if both still want it.",
      "A slightly fuller count, still scheduled, still cancellable. Do not do this as a surprise. Homework, not ambush.",
    ),
    body(
      "Twenty spanks you help put on the calendar",
      "You may lower the number on the day. You get a hand at the end. Cancelling with honesty still counts.",
      "Clothes on. 20. A hand to close.",
      "Say if you sit at work tomorrow. Two sets only if you still mean it.",
      "A fuller count, still scheduled. You may cancel without it becoming a story about you.",
    ),
  ),
  entry(
    "game",
    ["protocol", "training", "verbal"],
    "curious",
    body(
      "Yes, No, Ask — 10 minutes",
      "A kitchen timer. For 10 minutes they may only say yes, no, or ask. Ask means they need a bathroom, water, a stop, or a repeat. You ask simple questions they can answer with those words. This trains a Dominant to ask clearly, and a submissive to stay in a small language without going mute. If they use a full sentence because they need to, that is a win, not a fail. After: free speech, their name, water.",
      "5 minutes. Easy questions. Then free speech and names.",
      "10 minutes. You thank every ask. Then tea as people.",
      "15 minutes. If they freeze, you stop the game and hold the person. Freezing is data.",
    ),
    body(
      "Yes, No, Ask — you hold the small language",
      "You may say yes, no, or ask. Ask always works. A full sentence because you need it is a win. After: free speech, your name, water.",
      "5 minutes. Then your words back.",
      "10 minutes. Ask is always allowed.",
      "15 minutes. You may break into full sentences. That is care.",
    ),
  ),
  entry(
    "game",
    ["training", "protocol", "power-exchange"],
    "curious",
    body(
      "Repeat the instruction, then do it",
      "You say one short instruction. They say it back in their own words. Then they do it. If the repeat is wrong, you say it again, once, more clearly. This trains you to be clear, and them to listen without guessing. Three rounds. After: thank you, names, a drink. Do not add a trick instruction.",
      "3 easy rounds: sit, stand, drink water. Thank you.",
      "5 rounds. One of them may use their body (kneel, hands on thighs). Then names.",
      "8 rounds. If they miss, you own the miss as the speaker first. Then try one more, or stop.",
    ),
    body(
      "Repeat the instruction, then do it — you are the ears",
      "You hear it. You say it back. You do it. Guessing is not the game. After: thank you, your name, a drink.",
      "3 easy rounds. Then thank you.",
      "5 rounds. You may ask for a repeat.",
      "8 rounds. A miss can be their wording, not your failure.",
    ),
  ),
  entry(
    "game",
    ["protocol", "power-exchange"],
    "curious",
    body(
      "Red, yellow, green — a practice drill",
      "No scene. You are practising the words. You name a fake next step (a kiss, a smack, a toy). They say green (yes), yellow (slower / ask more), or red (stop). You obey the colour, even though nothing was going to happen. Do this 5 times. After: praise the reds. A red in practice is the whole point. Then tea.",
      "5 fake steps. Praise every colour, especially red. Tea.",
      "10 fake steps, mixed easy and spicy. Still no real scene. Still praise the reds.",
      "Do the drill, then run one real tiny green step you already planned — or stop on a yellow and call that a complete night.",
    ),
    body(
      "Red, yellow, green — you practise the words",
      "Fake steps. You say the colour. They obey it. A red is a win. After: tea.",
      "5 fake steps. Your red is praised.",
      "10 fake steps. Still no real scene.",
      "The drill, then one tiny real green — or a yellow that ends the night. Both count.",
    ),
  ),
  entry(
    "game",
    ["protocol", "training", "pet-play"],
    "curious",
    body(
      "Posture for 30 seconds, then talk",
      "They take a posture they already know: kneeling on a cushion, standing with hands behind, or sitting with a straight back. 30 seconds. You watch. Then they come out of it, and you both say one true thing: what the posture did in the head. This trains staying, and trains you to notice, not only to command. After: shake the body out. Water.",
      "Once. 30 seconds. One true sentence each. Water.",
      "Three times this week. Same posture. Compare the three sentences.",
      "Once a day, three days. If the body cannot kneel, pick a chair posture. Changing the posture is skill, not a fail.",
    ),
    body(
      "Posture for 30 seconds, then you talk",
      "A posture you already know. 30 seconds. Then one true thing about what it did in your head. After: shake out, water.",
      "Once. Then one true sentence.",
      "Three times this week. Compare the sentences.",
      "Three days. You may pick a chair if kneeling hurts.",
    ),
  ),
  entry(
    "game",
    ["protocol", "training", "praise"],
    "curious",
    body(
      "Three small wins on a card",
      "Write 3 tiny role wins on a card, for the week. Dominant examples: one clear instruction, one true praise, one on-time close. Submissive examples: one kneel, one honest yellow, one task ticked. Tick them when they happen. At the end of the week, read the ticks out loud and say thank you. Misses stay on the card as weather, not as a trial.",
      "Write 3 wins. Tick 1 this week. Read it out. Thank you.",
      "Tick all 3. Sunday read. Thank you both.",
      "Keep the same 3 next week if they helped, or write 3 new ones. Retiring a win is also a win.",
    ),
    body(
      "Three small wins on a card you help write",
      "Tiny, possible, ticked. Sunday you hear thank you. A miss is weather.",
      "Write 3. Tick 1. Hear thank you.",
      "Tick all 3. Sunday read.",
      "Keep or change them next week. You may retire one.",
    ),
  ),
  entry(
    "game",
    ["power-exchange", "brat-dynamic", "protocol"],
    "curious",
    body(
      "Who is in charge for 10 minutes",
      "A timer. For 10 minutes, one of you is clearly in charge. The other practises following, including a brat who still has to follow the clock. When it rings, you swap, or you stop. Say the swap out loud. This trains both seats without trapping anyone in one. After: names, a drink, one sentence about which seat was harder.",
      "10 minutes. One seat. Then names and a drink.",
      "10 minutes each. A spoken swap. Then both sentences.",
      "20 minutes in one seat, only if you both still want it. A brat testing the clock is still under the clock — or the game ends, and that is allowed.",
    ),
    body(
      "Who is in charge for 10 minutes — you practise both",
      "A timer. Follow, or lead, then swap. After: your name, a drink, which seat was harder.",
      "10 minutes. Then your name.",
      "10 minutes each. A spoken swap.",
      "20 minutes in one seat only if you still want it. You may end the game.",
    ),
  ),
  entry(
    "training",
    ["training", "protocol", "power-exchange"],
    "curious",
    body(
      "Kneeling clock — add it to Training",
      "A short exercise to train staying. They kneel on a cushion. You set a timer they can see. When it rings, you say their name and they stand. Log it in Training so you can run it again this week. If the body cannot kneel, use a chair with a straight back. Changing the posture is skill, not a fail. After: shake the legs out, water.",
      "30 seconds. Name. Stand. Log it in Training.",
      "60 seconds, once a day, three days this week. Same cushion. Log each one.",
      "2 minutes, three days. If they need to come up early, they say so. Thank the telling. Log the real time.",
    ),
    body(
      "Kneeling clock — you hold it, they log it",
      "Cushion. Timer you can see. Your name, then you stand. A chair is allowed. After: shake out, water.",
      "30 seconds. Then your name. They log it.",
      "60 seconds, three days. Same cushion.",
      "2 minutes, three days. You may come up early. That still gets logged.",
    ),
  ),
  entry(
    "training",
    ["training", "protocol", "service"],
    "curious",
    body(
      "Position names — present, kneel, stand",
      "Teach 3 names: present (hands on thighs, eyes down or on you — they pick), kneel (cushion), stand. You say the name once. They take the shape. You wait 10 seconds. Next name. Three rounds. This trains listening, not guessing. Log it in Training. After: their name, a drink, shake the body out.",
      "One round of the 3 names. Slow. Thank you. Log it.",
      "Three rounds. Same 3 names. If they miss, you say the name again, once, more clearly.",
      "Five rounds, or a 5-minute drill. No trick names. End on stand, then tea.",
    ),
    body(
      "Position names — you take the shape they named",
      "Present, kneel, stand. You hear the name. You take the shape. Guessing is not the drill. After: your name, a drink.",
      "One round of 3. Then thank you.",
      "Three rounds. You may ask for the name again.",
      "Five rounds. End on stand. Tea.",
    ),
  ),
  entry(
    "training",
    ["training", "protocol", "bondage"],
    "curious",
    body(
      "Hands still on their thighs",
      "No rope. They sit or kneel. Hands on their own thighs until the timer ends. If they move, you put the hand back once, kindly, or you stop. Stopping is allowed. Log the time they actually held in Training. After: they may move, their name, water.",
      "2 minutes on the sofa. Log it.",
      "5 minutes, three days this week. Log each hold.",
      "10 minutes, twice this week. Ordinary words if they need to move. Log the real time.",
    ),
    body(
      "Hands still on your thighs",
      "No rope. Hands on your thighs until the timer. You may say you need to move. After: your name, water.",
      "2 minutes. Then you may move.",
      "5 minutes, three days.",
      "10 minutes, twice. Ordinary words if you need to move.",
    ),
  ),
  entry(
    "training",
    ["training", "orgasm-control", "denial"],
    "practiced",
    body(
      "Edge count — stop at 8",
      "Your hand or a toy they already know. They say a number from 1 to 10. 8 means you stop. Do 3 stops. Log it in Training: how many stops, whether they came after. This trains them to speak, and you to listen. After: water, a towel, a clear yes or no about coming.",
      "3 stops. Clothes on. Then the planned yes or no. Log it.",
      "5 stops. Hands still if they can. They may still speak. Log it.",
      "A longer hold at 7 after the stops, then the planned yes or no. Log the real numbers, not the heroic ones.",
    ),
    body(
      "Edge count — you say 8, they stop",
      "You say the number. 8 means they stop. After: water, towel, a clear yes or no.",
      "3 stops. Then the planned yes or no.",
      "5 stops. You may still speak.",
      "A longer hold at 7. Log the real numbers.",
    ),
  ),
  entry(
    "training",
    ["training", "service", "protocol"],
    "curious",
    body(
      "Fetch and present",
      "You name one object in the room: a glass of water, a cushion, a toy they already use. They fetch it. They present it on open hands. You take it. You say thank you and their name. Three fetches. Log it in Training. After: they sit as a person. Do not add a fourth because the third was pretty.",
      "1 fetch. Water. Thank you. Name. Log it.",
      "3 fetches. Same rule. Then they sit.",
      "5 fetches, still in the house. If they use the adult voice, you answer the adult. Then sit.",
    ),
    body(
      "Fetch and present — you bring it",
      "You hear the object. You bring it on open hands. You get thank you and your name. After: you sit as a person.",
      "1 fetch. Water. Then you sit.",
      "3 fetches. Then you sit.",
      "5 fetches. Adult voice always works.",
    ),
  ),
  entry(
    "training",
    ["training", "protocol", "verbal"],
    "curious",
    body(
      "Honorific for one meal",
      "For one meal at home, they use a name they already said yes to: Sir, Ma'am, or another they picked. You use their name back with care. When the plates are down, legal names. Log it in Training: which meal, which name, how it felt. Do not use a name they did not pick. After: tea as people.",
      "5 minutes of the name at the table. Then legal names. Log it.",
      "One full meal. Legal names if anyone else can hear. Log it.",
      "Three meals this week. Sunday ask if the name still fits. Retiring it is also training.",
    ),
    body(
      "Honorific for one meal — you keep the name",
      "A name you already said yes to, for one meal. You get your legal name back. After: tea as yourself.",
      "5 minutes. Then your legal name.",
      "One full meal. You may ask for your legal name.",
      "Three meals. Sunday you may retire the name.",
    ),
  ),
  entry(
    "reward",
    ["orgasm-control", "praise", "sensation-play"],
    "curious",
    body(
      "They pick the orgasm — add it to Rewards",
      "A reward you can add in Rewards. When they cash it, they pick: your hand, their hand, a toy they already like, or being held with no orgasm. You run the one they picked. Do not swap it for a harder thing because you are in the mood. After: water, a towel, their name. Put it in Rewards with a point cost you both like.",
      "Add it. When they cash it: 10 unhurried minutes of what they picked. Then their name.",
      "Add it. When they cash it: they also pick the room and the music. You still run only what they named.",
      "Add it. When they cash it: a longer night of what they picked, still with a clock, still with a stop. Morning tea is part of the reward.",
    ),
    body(
      "You pick the orgasm — they add it to Rewards",
      "When you cash it, you pick. They run the one you named. After: water, towel, your name.",
      "10 unhurried minutes of what you picked.",
      "You also pick the room and the music.",
      "A longer night, still with a clock and a stop. Morning tea is part of it.",
    ),
  ),
  entry(
    "reward",
    ["service", "praise", "protocol"],
    "curious",
    body(
      "A bath they do not have to run",
      "Add this to Rewards. When they cash it, you run the water, check the heat with your hand, put a towel ready, and stay or step out — they pick. You do not turn it into a scene unless they ask. After: a robe, a drink, their name. The reward is being looked after, not performing.",
      "Add it. Cash: 15 minutes, you handle the water and the towel. Then their name.",
      "Add it. Cash: you wash their hair if they want. Then a robe and a drink.",
      "Add it. Cash: bath, hair, a quiet sit after. No extra tasks hiding in the aftercare.",
    ),
    body(
      "A bath you do not have to run",
      "When you cash it, they handle the water. You do not have to perform. After: a robe, a drink, your name.",
      "15 minutes. Water and towel. Then your name.",
      "Hair washed if you want. Then a robe.",
      "Bath, hair, a quiet sit. You may ask that this stay aftercare, not a scene.",
    ),
  ),
  entry(
    "reward",
    ["roleplay", "power-exchange", "ownership"],
    "curious",
    body(
      "A scene from a list of 3 they wrote",
      "Add this to Rewards. They write 3 scenes they actually want, while calm. When they cash it, they pick one. You run that one. You do not pick a fourth. Easy, hard, and extreme are how long and how full — not a bait-and-switch. After: their name, water, a check on whether it was the scene they meant.",
      "Add it. Cash: 15 minutes of the one they pick. Then names.",
      "Add it. Cash: 30 minutes of the one they pick. Then aftercare they named on the card.",
      "Add it. Cash: the fuller night of the one they pick, still with a clock and a stop. Morning note already drafted.",
    ),
    body(
      "A scene from a list of 3 you wrote",
      "You write 3. You pick 1 when you cash it. They run that one. After: your name, water.",
      "15 minutes of the one you pick.",
      "30 minutes, plus the aftercare you named.",
      "The fuller night, still with a clock. You may still stop it.",
    ),
  ),
  entry(
    "reward",
    ["protocol", "power-exchange", "ownership"],
    "curious",
    body(
      "A free evening — no protocol",
      "Add this to Rewards. When they cash it, names go back to ordinary, kneeling is off, honorifics are off, unless they ask for one small thing. You do not sulk. You do not sneak a rule back in. After: in the morning you both say whether you missed the structure or enjoyed the air. Both answers are allowed.",
      "Add it. Cash: 1 hour as people. Then you may put one small rule back, if they want it.",
      "Add it. Cash: a whole evening. Phones, food, a show. No extra ritual.",
      "Add it. Cash: a full day off protocol. A collar, if they wear one, comes off with their real name. On again only if they ask.",
    ),
    body(
      "A free evening — you cash the off-switch",
      "When you cash it, you are a person. Rules stay off unless you ask. After: say in the morning if you missed them.",
      "1 hour as yourself.",
      "A whole evening. No extra ritual.",
      "A full day. You decide if anything goes back on.",
    ),
  ),
  entry(
    "reward",
    ["sensation-play", "orgasm-control", "praise"],
    "curious",
    body(
      "The toy they have been asking for",
      "Add this to Rewards. When they cash it, you use the toy they have been wanting, the way they like, for a time you both named while calm. You do not swap it for a 'better' toy. After: wash, water, their name. Put the toy's name on the Rewards card so nobody 'forgets'.",
      "Add it. Cash: 10 minutes of that toy, their pace. Then wash and their name.",
      "Add it. Cash: 20 minutes. They may ask you to slow down. You slow down.",
      "Add it. Cash: a longer session, still the named toy, still a clock. A second toy only if they ask.",
    ),
    body(
      "The toy you have been asking for",
      "When you cash it, you get that toy, that way, that time. After: wash, water, your name.",
      "10 minutes, your pace.",
      "20 minutes. You may ask them to slow down.",
      "Longer, still the named toy. A second toy only if you ask.",
    ),
  ),
  entry(
    "reward",
    ["service", "praise"],
    "curious",
    body(
      "You serve them breakfast",
      "Add this to Rewards. When they cash it, you make a simple breakfast they already eat. They stay in bed or on the sofa. You bring it. You sit. This is not a humiliation meal unless that is on a written list. After: plates in the sink can wait. Their name. A normal morning.",
      "Add it. Cash: tea or coffee in bed. Then their name.",
      "Add it. Cash: a simple plate plus a drink. You sit with them.",
      "Add it. Cash: breakfast, then 20 minutes of doing the small chores so they do not have to. Still a thank you, not a speech.",
    ),
    body(
      "They serve you breakfast",
      "When you cash it, they bring a simple breakfast. You do not have to perform. After: your name. A normal morning.",
      "Tea or coffee in bed. Then your name.",
      "A simple plate plus a drink. They sit with you.",
      "Breakfast, then 20 minutes where they take the small chores. You may still get up if you want to.",
    ),
  ),
  entry(
    "punishment",
    ["protocol", "training", "power-exchange"],
    "curious",
    body(
      "Corner time — add it to Punishments",
      "A punishment you can add in Punishments. Not a surprise. They stand or sit facing a wall, in the house, for a time you both named while calm. You stay in the room. They can speak. A red ends it. After: their name, a hand on their back, water. Put the minutes on the card. Do not add extra minutes because you are still annoyed.",
      "Add it. Run: 2 minutes. Then name, hand, water.",
      "Add it. Run: 5 minutes. You stay. Then name and water.",
      "Add it. Run: 10 minutes, only if they have done 5 and the card still says 10. Same aftercare. No extra task stacked on after.",
    ),
    body(
      "Corner time — they add it, you take it",
      "A time you agreed while calm. You can speak. A red ends it. After: your name, a hand, water.",
      "2 minutes. Then your name.",
      "5 minutes. They stay in the room.",
      "10 minutes only if you have done 5. You may still red.",
    ),
  ),
  entry(
    "punishment",
    ["protocol", "training", "verbal"],
    "curious",
    body(
      "Written lines — add it to Punishments",
      "Add this to Punishments. They write a short true line, by hand, a set number of times. The line is about the miss, not about their worth. Example: I will say yellow when I need to. Not: I am bad. You read them. You say thank you. After: the page goes in a drawer, or you tear it up together if they want it gone. Do not hang it on a fridge a guest can see.",
      "Add it. Run: 5 lines. You read. Thank you. Drawer or tear.",
      "Add it. Run: 10 lines. Same rule. Then tea as people.",
      "Add it. Run: 20 lines, only if 10 still felt like repair, not like shame. If it shames, you stop and hold the person.",
    ),
    body(
      "Written lines — you write the true one",
      "A short true line about the miss, not about your worth. After: they read, they thank you, drawer or tear.",
      "5 lines. Then tea.",
      "10 lines. Then tea as yourself.",
      "20 only if 10 still felt like repair. You may stop if it shames.",
    ),
  ),
  entry(
    "punishment",
    ["spanking", "impact-play", "sadomasochism"],
    "practiced",
    body(
      "Counted hand spanking — add it to Punishments",
      "Add this to Punishments with a number you both wrote while calm. Clothes on first. Hand only unless the card names a paddle you already know. They may lower the number on the day. They may not raise it because the afternoon was bad. Count out loud. After: sit them up, water, a hand on their back, their name. This is homework, not a blow-up.",
      "Add it. Run: 10, clothes on. Sit up. Water. Name.",
      "Add it. Run: the number on the card, underwear if they asked. Hand to close.",
      "Add it. Run: still the card number, bare only if the card says so. Marks that show at work need a separate yes. Landing is longer than the spanking.",
    ),
    body(
      "Counted hand spanking — you take the number on the card",
      "You may lower it on the day. You get a hand at the end. After: sit up, water, your name.",
      "10, clothes on. Then sit up.",
      "The card number. Underwear if you asked.",
      "Bare only if the card says so. You still get the long landing.",
    ),
  ),
  entry(
    "punishment",
    ["orgasm-control", "denial", "chastity"],
    "practiced",
    body(
      "No toy tonight — add it to Punishments",
      "Add this to Punishments. When it is cashed, toys stay in the drawer for the evening. Hands, kissing, and being held are still allowed unless the card says otherwise. You do not add a sneer. After: a kind close so they are not left as a problem. Put one planned yes on the calendar so this does not become a week of only no.",
      "Add it. Run: one evening. Hands and holding still yes. Kind close.",
      "Add it. Run: two evenings this week, not stacked on a bad day. A planned yes still on the week.",
      "Add it. Run: 24 hours. Still a planned yes after. If the wait turns lonely, shorten it.",
    ),
    body(
      "No toy tonight — you take the drawer rule",
      "Toys away. Hands and holding still allowed unless the card says no. You still get a kind close.",
      "One evening. Then a kind close.",
      "Two evenings, not on a piled-up day. A planned yes still exists.",
      "24 hours. Say if the wait is lonely. They should shorten it.",
    ),
  ),
  entry(
    "punishment",
    ["protocol", "training", "service"],
    "curious",
    body(
      "Extra kneel before the next meal",
      "Add this to Punishments. One extra kneel, on a cushion, before the next meal you already eat together. Timer they can see. You say their name. They stand. You eat. Do not stack a second extra. After: ordinary meal. Log it so it does not happen twice for the same miss.",
      "Add it. Run: 30 seconds. Name. Stand. Eat.",
      "Add it. Run: 60 seconds. Then the meal as people.",
      "Add it. Run: 2 minutes, only if 60 seconds still felt like repair. Then eat. No speech about the miss at the table.",
    ),
    body(
      "Extra kneel before the next meal — you hold it",
      "One extra. Cushion. Timer. Your name. Stand. Eat. It does not happen twice for the same miss.",
      "30 seconds. Then eat.",
      "60 seconds. Then the meal as yourself.",
      "2 minutes only if 60 still felt like repair. No speech about the miss at the table.",
    ),
  ),
  entry(
    "punishment",
    ["protocol", "ownership", "power-exchange"],
    "curious",
    body(
      "A 24-hour pause on one named privilege",
      "Add this to Punishments. Name one small privilege while calm: choosing the show, a pet name, a toy, a late bedtime. When it is cashed, that one thing pauses for 24 hours. Everything else stays. You do not add a second pause because you are still mad. After: the privilege comes back out loud, with their name. Put the privilege's name on the card.",
      "Add it. Run: 24 hours off one small thing. Then it comes back with their name.",
      "Add it. Run: the same, plus one check-in at the halfway point: still fair?",
      "Add it. Run: 48 hours only if they have done 24 and the card says 48. If it starts to feel like exile, you end it early and say so.",
    ),
    body(
      "A 24-hour pause on one privilege you named",
      "One named thing. Everything else stays. It comes back out loud, with your name.",
      "24 hours. Then it comes back.",
      "24 hours, plus a halfway check: still fair?",
      "48 hours only if the card says so. You may ask to end it early.",
    ),
  ),
  entry(
    "kink",
    ["bondage", "rope"],
    "curious",
    body(
      "Wrists wrapped, a bow they can undo",
      "A scarf or a soft rope they already know. Wrists in front. A bow they can undo with their teeth or a free finger. You stay in the room. Timer they can see. Scissors in reach. After: undo, rub wrists, water, say they could have left. This is the bondage on your profile, kept small.",
      "5 minutes. Bow they can undo. Then off. Rub wrists.",
      "15 minutes. Check halfway that fingers are warm and pink, not blue.",
      "30 minutes. Same bow. Still a timer. No gag and no ankles at the same time tonight.",
    ),
    body(
      "Wrists wrapped, a bow you can undo",
      "You can undo it. You can leave. Staying is the scene. After: wrists rubbed, water.",
      "5 minutes. Then off.",
      "15 minutes. Say if fingers tingle.",
      "30 minutes. You may refuse a gag or ankles tonight.",
    ),
  ),
  entry(
    "kink",
    ["spanking", "impact-play", "sadomasochism"],
    "practiced",
    body(
      "A counted spanking, clothes on first",
      "The spanking and impact on your profile, run as a small set. Clothes on first. Hand, or a paddle you already know. Number written while calm. Count out loud. They may lower it. After: sit up, water, a hand on their back, look at the skin. Do not add a second tool.",
      "Clothes on. 10, check, 10. Sit up. Water.",
      "Underwear if they asked. Same written number. Hand to close.",
      "Bare if they asked. Marks that show at work need a separate yes. Landing is 15 minutes.",
    ),
    body(
      "A counted spanking you take, clothes on first",
      "You may lower the number. You get a hand at the end. After: sit up, water.",
      "Clothes on. 10, check, 10.",
      "Underwear if you asked. Same number.",
      "Bare if you asked. Say if you sit at work tomorrow.",
    ),
  ),
  entry(
    "kink",
    ["protocol", "power-exchange", "ownership"],
    "curious",
    body(
      "One house rule on a card",
      "The protocol and power exchange on your profile, as one rule. Written. Small enough for a real life. Examples: phone on the table at dinner, water before coffee, ask before you come to bed. Run it for one evening. Thank more than you catch. Then take the card down. Ask if it lives.",
      "Write the rule. Run it for 1 hour. Release on time. Tea.",
      "One evening. Catch once, kindly, or not at all. Then the card away.",
      "Keep it for the week if you both liked it. Ending a rule is also protocol.",
    ),
    body(
      "One house rule on a card you can keep",
      "One rule you can live inside. A miss you report is not a fail. The card comes down.",
      "1 hour. Then tea as yourself.",
      "One evening. Then the card away.",
      "A week if you want it. You may also retire it.",
    ),
  ),
  entry(
    "kink",
    ["service"],
    "curious",
    body(
      "They serve one small thing, then they sit",
      "The service on your profile, kept to one act: pour water, fold a throw, bring a towel. They do it. You thank them. They sit as a person. Do not stack a second job because the first was easy. After: drink together.",
      "One job. Thank you. Sit. Drink.",
      "Three small jobs on a card. Then the card away and they sit.",
      "A 30-minute window of small jobs you already need done. Then they sit, and you do not add more.",
    ),
    body(
      "You serve one small thing, then you sit",
      "One act. You get thank you. You sit as a person. After: drink together.",
      "One job. Then you sit.",
      "Three small jobs. Then you sit.",
      "30 minutes of jobs you already need. Then you sit. You may use the adult voice.",
    ),
  ),
  entry(
    "kink",
    ["pet-play", "ownership"],
    "curious",
    body(
      "A cushion, a bowl of water, a name that comes back",
      "The pet play on your profile. They sit on a cushion. You offer water. A pet name only if they asked for one. 10 minutes in the house. Then their real name and the sofa. No outdoor leads. No cages. If they laugh from discomfort, the pet is over and the person is held.",
      "5 minutes. Cushion. Water. Real name. Snack.",
      "10 minutes. Jewellery on, then off with their name.",
      "20 minutes in the house only. Legal name if anyone else can hear.",
    ),
    body(
      "You sit on a cushion. Your name comes back",
      "Water. A pet name only if you asked. Then your real name and the sofa.",
      "5 minutes. Then your name and a snack.",
      "10 minutes. Then your name.",
      "20 minutes. You may use the adult voice.",
    ),
  ),
  entry(
    "kink",
    ["praise", "verbal"],
    "curious",
    body(
      "Three true praises, spoken",
      "The praise and verbal play on your profile. Say 3 true sentences about how they were today. Be specific. Do not turn praise into a new task. If it starts to sound like shame, make it smaller, or stop. After: they only have to hear it. The words can live in a message.",
      "3 lines, one night. Stop means stop.",
      "3 nights this week. No extra tasks attached.",
      "Every night this week. Sunday keep the lines that landed.",
    ),
    body(
      "Three true praises you have to take",
      "You hear 3 true lines. You may say stop. The message can stay.",
      "One night. Thank you, or stop.",
      "Three nights.",
      "Every night. Say on Sunday which line helped.",
    ),
  ),
  entry(
    "kink",
    ["humiliation", "degradation", "verbal"],
    "seasoned",
    body(
      "Playful mean words from a page, then kindness",
      "The humiliation and degradation on your profile, kept on a page. While clothed, write 5 lines they want. Only those. Read once. Stop. Then the opposite kind sentences, as true. If anyone laughs from discomfort, it is over. Do not do this in public. Morning note already drafted.",
      "The 5 lines once. Then the 5 kind opposites.",
      "One line, repeated, then its opposite. Morning note drafted.",
      "The full list, still once, still with repair the same night. No spanking stacked on.",
    ),
    body(
      "Playful mean words from a page you helped write",
      "Only the page. You can stop it. After: the opposite sentences.",
      "The 5 lines once. Then kindness.",
      "One line, then its opposite. You may stop after the first.",
      "The full list, still once. You may keep it on paper and not run it.",
    ),
  ),
  entry(
    "kink",
    ["orgasm-control", "denial", "chastity"],
    "practiced",
    body(
      "They ask before they come",
      "The orgasm control, denial, or chastity on your profile, as a week rule. They ask before they come. You answer the same day. Yes, not yet, or tomorrow. If the answer is no, you still owe warmth. Put one planned yes on the calendar so the week is not only waiting. Sunday read it like weather, not like evidence.",
      "One evening. They ask once. You answer. If no, a kind text and a show you know.",
      "Three days. One planned yes. Ordinary language only.",
      "The whole week. One planned yes. Sunday decide if it lives.",
    ),
    body(
      "You ask before you come",
      "Asking is the kink. You get an answer the same day. Warmth is still owed if the answer is no.",
      "One evening. Ask once.",
      "Three days. A planned yes on the calendar.",
      "The week. Say on Sunday if the waiting was hot or just lonely.",
    ),
  ),
  entry(
    "kink",
    ["exhibitionism", "voyeurism"],
    "curious",
    body(
      "They show you, in the house, on purpose",
      "The exhibitionism or voyeurism on your profile, with no strangers. They take off as much as they want. You look. You do not touch until they say so, or you do not touch at all — they pick. 10 minutes. No photos unless that is a second yes. After: clothes, their name, a drink.",
      "Clothes half off. You look for 2 minutes. Then their name.",
      "They pick what comes off. You look. Touch only if they say. Then clothes and a drink.",
      "A longer look, still in the house. A mirror if they want to see themselves being seen. Still no photos unless they asked.",
    ),
    body(
      "You show them, in the house, on purpose",
      "You pick what comes off. They look. Touch only if you say. After: clothes, your name, a drink.",
      "Clothes half off. 2 minutes. Then your name.",
      "You pick. They look. You say if they may touch.",
      "A longer look. A mirror if you want it. You may refuse photos.",
    ),
  ),
  entry(
    "kink",
    ["roleplay"],
    "curious",
    body(
      "Ten minutes in a role you already named",
      "The roleplay on your profile. Pick a role you have already talked about. A timer. 10 minutes. When it rings, legal names. Silly is allowed. After: water, a sentence about whether the role still fits.",
      "5 minutes. One line each. Timer. Names.",
      "10 minutes. Then names and tea.",
      "20 minutes, still a timer, still names back. No extra kink stacked on unless it was in the plan.",
    ),
    body(
      "Ten minutes in a role you already named — you enter it",
      "A role you have already talked about. A timer. Then your legal name.",
      "5 minutes. Then your name.",
      "10 minutes. Then tea.",
      "20 minutes. You may stop with ordinary words.",
    ),
  ),
  entry(
    "kink",
    ["primal"],
    "practiced",
    body(
      "A short chase in the house",
      "The primal play on your profile. At home. You count down from 5. They run to another room. You follow. You catch them with arms, not with pain, unless impact is also on the card. 3 minutes. Then hold, breath, their name. No stairs. No glass. No outdoor chase.",
      "One countdown. One catch. Hold. Name. Water.",
      "Three short chases. Same house rules. Then a long hold.",
      "A 10-minute hunt, still in the house, still a stop word. After: blanket, water, names. If anyone is actually scared, it is over.",
    ),
    body(
      "A short chase in the house — you run, you get caught",
      "Home only. Arms, not pain, unless you asked. After: hold, breath, your name.",
      "One countdown. One catch. Hold.",
      "Three short chases. Then a long hold.",
      "A 10-minute hunt. You may stop with ordinary words. Scared means over.",
    ),
  ),
  entry(
    "kink",
    ["sensation-play", "temperature-play"],
    "curious",
    body(
      "Warm hands, then a cool spoon",
      "The sensation or temperature play on your profile. Warm oil or warm hands, then the back of a metal spoon run under cold water. On skin they offered. Ask after each pass: more, less, or somewhere else. No boiling. No spoon on nipples or genitals unless they asked while calm. After: towel, blanket, a warm drink.",
      "Clothes on. Shoulders. 5 minutes. Stop at the first enough.",
      "One area at a time, clothes as they like. End with a towel.",
      "A longer map they named in advance. This can be the whole night. You do not have to have sex after.",
    ),
    body(
      "Warm hands, then a cool spoon on you",
      "On skin you offered. Say more, less, or somewhere else. After: towel, blanket, a warm drink.",
      "Clothes on. Shoulders. 5 minutes.",
      "One area at a time. End with a towel.",
      "A longer map you named. You do not have to have sex after.",
    ),
  ),
  entry(
    "kink",
    ["sensory-deprivation"],
    "practiced",
    body(
      "A blindfold they can take off",
      "The sensory deprivation on your profile. A sleep mask or a scarf they can pull down. You stay talking so they know where you are. Timer they agreed. After: light back, their name, water, sit. Do not add a gag the first time. Do not leave the room.",
      "2 minutes. They can pull it down. Then name and water.",
      "5 minutes. You keep talking. Then light, name, sit.",
      "10 minutes only if they have done 5. Still able to take it off. Still you in the room.",
    ),
    body(
      "A blindfold you can take off",
      "You can pull it down. They stay. After: light, your name, water.",
      "2 minutes. Then your name.",
      "5 minutes. They keep talking.",
      "10 minutes only if you have done 5. You may take it off early.",
    ),
  ),
  entry(
    "kink",
    ["brat-dynamic"],
    "curious",
    body(
      "One poke, then they take the answer",
      "The brat dynamic on your profile. They get one poke: a sass, a delay, a grin. You answer once, clearly — a look, a number, a hold. Then the poke is over and the evening continues. This trains a brat to poke on purpose, and a tamer to answer without a spiral. After: names, a drink, a laugh if there is one.",
      "One poke. One answer. Drink.",
      "Three pokes this week, not stacked in one hour. Each one gets one answer.",
      "A named brat window of 10 minutes, then they drop it on the timer. If they cannot drop it, you pause the dynamic and hold the person.",
    ),
    body(
      "One poke, then you take the answer",
      "One poke on purpose. You take the one answer. Then the evening continues.",
      "One poke. One answer. Drink.",
      "Three pokes this week. Not stacked.",
      "A 10-minute window, then you drop it. You may ask to pause the dynamic.",
    ),
  ),
  entry(
    "kink",
    ["marking"],
    "practiced",
    body(
      "A hickey they asked for, where they said",
      "The marking on your profile. A suck-mark on a place they named. Agree if it may show tomorrow. Do not break the skin. After: look together, ice or nothing. Photo only with a yes they still mean.",
      "One small mark. Sit and look. Ordinary evening.",
      "A place they can cover. Ask about tomorrow before you start.",
      "A place they want to see in the mirror. Still one mark. Do not add another because the first looked pretty.",
    ),
    body(
      "A hickey you asked for, where you said",
      "You name the place. You name whether it may show. After: look, then ordinary evening or ice.",
      "One small mark. Look. Ordinary evening.",
      "A place you can cover. Say if you work tomorrow.",
      "A place you want to see. You may ask that one is enough.",
    ),
  ),
  entry(
    "kink",
    ["objectification"],
    "practiced",
    body(
      "A furniture minute — they hold still, then they are a person",
      "The objectification on your profile, with a clock. They kneel or sit as a table or a footrest for a time you both named — no weight that hurts. You do not pile things that will fall. When the timer rings, you say their name first, then thank you. After: they sit as a person, water, a check on whether it felt hot or just unused. Repair the second.",
      "1 minute. Then their name, thank you, sit.",
      "5 minutes. You stay in the room. Then name and water.",
      "10 minutes, only if 5 still felt like play. If they go quiet in a way that is not heat, you end it and hold the person.",
    ),
    body(
      "A furniture minute — you hold still, then you are a person",
      "A clock. Your name comes back first. After: sit as yourself, water.",
      "1 minute. Then your name.",
      "5 minutes. They stay. Then water.",
      "10 minutes only if 5 still felt like play. You may end it.",
    ),
  ),
  entry(
    "kink",
    ["cnc", "breath-play"],
    "established",
    body(
      "Want, fear, out — write the edge, do not run it",
      "The CNC or breath play on your profile. You do not run it tonight. You write it. Wanting is not consent for tonight. Three columns: want, fear, out. Sleep on it. Closing the notebook is aftercare. If it is still a yes in the morning, it goes on a calendar, not into the next hour.",
      "Want / fear / out. Tea. Closed. No scene.",
      "A fuller page: aftercare, what never happens, who would know you are planning (not doing). Still no scene.",
      "Morning read. Calendar only after sleep — or the page scares you, and that is a complete answer.",
    ),
    body(
      "Want, fear, out — you write the edge, you do not have to be brave tonight",
      "You write. You do not run it tonight. Closing the notebook is aftercare.",
      "Want / fear / out. Tea. Closed.",
      "A fuller page. Still no scene. Still sleep.",
      "Morning read. You may refuse the calendar.",
    ),
  ),
];
