/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as GamesRouteImport } from './routes/games'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as HouseRouteImport } from './routes/house'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PunishmentsRouteImport } from './routes/punishments'
import { Route as RabbitsRouteImport } from './routes/rabbits'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as RoleplayRouteImport } from './routes/roleplay'
import { Route as ScenesRouteImport } from './routes/scenes'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ToysRouteImport } from './routes/toys'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRoute = HouseRouteImport.update({
  id: '/house',
  path: '/house',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PunishmentsRoute = PunishmentsRouteImport.update({
  id: '/punishments',
  path: '/punishments',
  getParentRoute: () => rootRouteImport,
} as any)
const RabbitsRoute = RabbitsRouteImport.update({
  id: '/rabbits',
  path: '/rabbits',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleplayRoute = RoleplayRouteImport.update({
  id: '/roleplay',
  path: '/roleplay',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenesRoute = ScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => rootRouteImport,
} as any)
const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ToysRoute = ToysRouteImport.update({
  id: '/toys',
  path: '/toys',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/challenges': typeof ChallengesRoute
  '/games': typeof GamesRoute
  '/habits': typeof HabitsRoute
  '/house': typeof HouseRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/profile': typeof ProfileRoute
  '/punishments': typeof PunishmentsRoute
  '/rabbits': typeof RabbitsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/roleplay': typeof RoleplayRoute
  '/scenes': typeof ScenesRoute
  '/talk': typeof TalkRoute
  '/tasks': typeof TasksRoute
  '/toys': typeof ToysRoute
  '/training': typeof TrainingRoute
  '/wishlist': typeof WishlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/challenges': typeof ChallengesRoute
  '/games': typeof GamesRoute
  '/habits': typeof HabitsRoute
  '/house': typeof HouseRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/profile': typeof ProfileRoute
  '/punishments': typeof PunishmentsRoute
  '/rabbits': typeof RabbitsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/roleplay': typeof RoleplayRoute
  '/scenes': typeof ScenesRoute
  '/talk': typeof TalkRoute
  '/tasks': typeof TasksRoute
  '/toys': typeof ToysRoute
  '/training': typeof TrainingRoute
  '/wishlist': typeof WishlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/challenges': typeof ChallengesRoute
  '/games': typeof GamesRoute
  '/habits': typeof HabitsRoute
  '/house': typeof HouseRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/profile': typeof ProfileRoute
  '/punishments': typeof PunishmentsRoute
  '/rabbits': typeof RabbitsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/roleplay': typeof RoleplayRoute
  '/scenes': typeof ScenesRoute
  '/talk': typeof TalkRoute
  '/tasks': typeof TasksRoute
  '/toys': typeof ToysRoute
  '/training': typeof TrainingRoute
  '/wishlist': typeof WishlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/challenges'
    | '/games'
    | '/habits'
    | '/house'
    | '/journal'
    | '/login'
    | '/notes'
    | '/playbook'
    | '/profile'
    | '/punishments'
    | '/rabbits'
    | '/reset-password'
    | '/rewards'
    | '/roleplay'
    | '/scenes'
    | '/talk'
    | '/tasks'
    | '/toys'
    | '/training'
    | '/wishlist'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/challenges'
    | '/games'
    | '/habits'
    | '/house'
    | '/journal'
    | '/login'
    | '/notes'
    | '/playbook'
    | '/profile'
    | '/punishments'
    | '/rabbits'
    | '/reset-password'
    | '/rewards'
    | '/roleplay'
    | '/scenes'
    | '/talk'
    | '/tasks'
    | '/toys'
    | '/training'
    | '/wishlist'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/challenges'
    | '/games'
    | '/habits'
    | '/house'
    | '/journal'
    | '/login'
    | '/notes'
    | '/playbook'
    | '/profile'
    | '/punishments'
    | '/rabbits'
    | '/reset-password'
    | '/rewards'
    | '/roleplay'
    | '/scenes'
    | '/talk'
    | '/tasks'
    | '/toys'
    | '/training'
    | '/wishlist'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  ChallengesRoute: typeof ChallengesRoute
  GamesRoute: typeof GamesRoute
  HabitsRoute: typeof HabitsRoute
  HouseRoute: typeof HouseRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  PlaybookRoute: typeof PlaybookRoute
  ProfileRoute: typeof ProfileRoute
  PunishmentsRoute: typeof PunishmentsRoute
  RabbitsRoute: typeof RabbitsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  RoleplayRoute: typeof RoleplayRoute
  ScenesRoute: typeof ScenesRoute
  TalkRoute: typeof TalkRoute
  TasksRoute: typeof TasksRoute
  ToysRoute: typeof ToysRoute
  TrainingRoute: typeof TrainingRoute
  WishlistRoute: typeof WishlistRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house': {
      id: '/house'
      path: '/house'
      fullPath: '/house'
      preLoaderRoute: typeof HouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punishments': {
      id: '/punishments'
      path: '/punishments'
      fullPath: '/punishments'
      preLoaderRoute: typeof PunishmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rabbits': {
      id: '/rabbits'
      path: '/rabbits'
      fullPath: '/rabbits'
      preLoaderRoute: typeof RabbitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roleplay': {
      id: '/roleplay'
      path: '/roleplay'
      fullPath: '/roleplay'
      preLoaderRoute: typeof RoleplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenes': {
      id: '/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof ScenesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toys': {
      id: '/toys'
      path: '/toys'
      fullPath: '/toys'
      preLoaderRoute: typeof ToysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  ChallengesRoute: ChallengesRoute,
  GamesRoute: GamesRoute,
  HabitsRoute: HabitsRoute,
  HouseRoute: HouseRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  PlaybookRoute: PlaybookRoute,
  ProfileRoute: ProfileRoute,
  PunishmentsRoute: PunishmentsRoute,
  RabbitsRoute: RabbitsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  RoleplayRoute: RoleplayRoute,
  ScenesRoute: ScenesRoute,
  TalkRoute: TalkRoute,
  TasksRoute: TasksRoute,
  ToysRoute: ToysRoute,
  TrainingRoute: TrainingRoute,
  WishlistRoute: WishlistRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
